### ISSUE TITLE
Windows 系统安装 PyYAML 依赖包时出现 UnicodeDecodeError

### ISSUE THREAD

**Issue by imzengyang** [HttpRunner/HttpRunner#107]
python：3.6.3  64bit
os： windows 10 64bit

安装方式：
pip install httprunner 

报错
```
C:\Users\zengyang>pip install httprunner
Collecting httprunner
  Downloading HttpRunner-0.9.7.tar.gz
Requirement already satisfied: requests in c:\users\zengyang\appdata\local\programs\python\python36\lib\site-packages (from httpr
)
Collecting PyYAML (from httprunner)
  Downloading PyYAML-3.12.tar.gz (253kB)
    100% |████████████████████████████████| 256kB 618kB/s
Requirement already satisfied: Jinja2 in c:\users\zengyang\appdata\local\programs\python\python36\lib\site-packages (from httprun
Collecting har2case (from httprunner)
  Downloading har2case-0.1.4.tar.gz
Requirement already satisfied: colorama in c:\users\zengyang\appdata\local\programs\python\python36\lib\site-packages (from httpr
)
Collecting colorlog (from httprunner)
  Downloading colorlog-3.1.2-py2.py3-none-any.whl
Requirement already satisfied: idna<2.7,>=2.5 in c:\users\zengyang\appdata\local\programs\python\python36\lib\site-packages (from
ests->httprunner)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\zengyang\appdata\local\programs\python\python36\lib\site-packages (
requests->httprunner)
Requirement already satisfied: urllib3<1.23,>=1.21.1 in c:\users\zengyang\appdata\local\programs\python\python36\lib\site-package
om requests->httprunner)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in c:\users\zengyang\appdata\local\programs\python\python36\lib\site-package
om requests->httprunner)
Requirement already satisfied: MarkupSafe>=0.23 in c:\users\zengyang\appdata\local\programs\python\python36\lib\site-packages (fr
nja2->httprunner)
Installing collected packages: PyYAML, har2case, colorlog, httprunner
  Running setup.py install for PyYAML ... error
Exception:
Traceback (most recent call last):
  File "c:\users\zengyang\appdata\local\programs\python\python36\lib\site-packages\pip\compat\__init__.py", line 73, in console_t

    return s.decode(sys.__stdout__.encoding)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xce in position 72: invalid continuation byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\zengyang\appdata\local\programs\python\python36\lib\site-packages\pip\basecommand.py", line 215, in main
    status = self.run(options, args)
  File "c:\users\zengyang\appdata\local\programs\python\python36\lib\site-packages\pip\commands\install.py", line 342, in run
    prefix=options.prefix_path,
  File "c:\users\zengyang\appdata\local\programs\python\python36\lib\site-packages\pip\req\req_set.py", line 784, in install
    **kwargs
  File "c:\users\zengyang\appdata\local\programs\python\python36\lib\site-packages\pip\req\req_install.py", line 878, in install
    spinner=spinner,
  File "c:\users\zengyang\appdata\local\programs\python\python36\lib\site-packages\pip\utils\__init__.py", line 676, in call_subp
s
    line = console_to_str(proc.stdout.readline())
  File "c:\users\zengyang\appdata\local\programs\python\python36\lib\site-packages\pip\compat\__init__.py", line 75, in console_t

    return s.decode('utf_8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xce in position 72: invalid continuation byte
```

**Comment by debugtalk** [comment]
@imzengyang 看日志你是安装 PyYAML 时出的问题，[这里](https://github.com/pypa/pip/issues/4998)有个跟你类似的，你参考下。
