### ISSUE TITLE
查看报告提示 OSError: [WinError 6] 句柄无效

### ISSUE THREAD

**Issue by zuokexia** [httprunner/httprunner#1074]
> ## 问题描述
> 执行命令后，查看报告提示 OSError: [WinError 6] 句柄无效。
> 
> hrun demo/testcases/createFolder_test.py --html=demo/reports/report.html
> 
> ## 版本信息
> 请提供如下版本信息：
> 
> httprunner版本：3.1.4
> os: window10
> python 3.7.1
> 
> 错误信息
> --- Logging error in Loguru Handler #0 ---
> Record was: {'elapsed': datetime.timedelta(seconds=2, microseconds=797505), 'exception': None, 'extra': {}, 'file': (name='loader.py', path='c:\users\lnz\pycharmprojects\httprunner_study\venv\lib\site-packages\httprunner\loader.py'), 'function': 'load_dot_env_file', 'level': (name='INFO', no=20, icon='ℹ️'), 'line': 127, 'message': 'Loading environment variables from C:\Users\lnz\PycharmProjects\httprunner_study\demo\.env', 'module': 'loader', 'name': 'httprunner.loader', 'process': (id=25780, name='MainProcess'), 'thread': (id=14432, name='MainThread'), 'time': datetime(2020, 7, 25, 17, 43, 27, 794163, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800), '中国标准时间'))}
> Traceback (most recent call last):
> File "c:\users\lnz\pycharmprojects\httprunner_study\venv\lib\site-packages\loguru_handler.py", line 177, in emit
> self._sink.write(str_record)
> File "c:\users\lnz\pycharmprojects\httprunner_study\venv\lib\site-packages\loguru_simple_sinks.py", line 26, in write
> self._stream.write(message)
> File "c:\users\lnz\pycharmprojects\httprunner_study\venv\lib\site-packages\colorama\ansitowin32.py", line 41, in write
> self.__convertor.write(text)
> File "c:\users\lnz\pycharmprojects\httprunner_study\venv\lib\site-packages\colorama\ansitowin32.py", line 162, in write
> self.write_and_convert(text)
> File "c:\users\lnz\pycharmprojects\httprunner_study\venv\lib\site-packages\colorama\ansitowin32.py", line 187, in write_and_convert
> self.write_plain_text(text, cursor, start)
> File "c:\users\lnz\pycharmprojects\httprunner_study\venv\lib\site-packages\colorama\ansitowin32.py", line 196, in write_plain_text
> self.wrapped.flush()
> OSError: [WinError 6] 句柄无效。
> --- End of logging error ---
> --- Logging error in Loguru Handler #0 ---
> Record was: {'elapsed': datetime.timedelta(seconds=2, microseconds=800498), 'exception': None, 'extra': {}, 'file': (name='utils.py', path='c:\users\lnz\pycharmprojects\httprunner_study\venv\lib\site-packages\httprunner\utils.py'), 'function': 'set_os_environ', 'level': (name='DEBUG', no=10, icon='🐞'), 'line': 33, 'message': 'Set OS environment variable: USERNAME', 'module': 'utils', 'name': 'httprunner.utils', 'process': (id=25780, name='MainProcess'), 'thread': (id=14432, name='MainThread'), 'time': datetime(2020, 7, 25, 17, 43, 27, 797156, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800), '中国标准时间'))}
> Traceback (most recent call last):
> File "c:\users\lnz\pycharmprojects\httprunner_study\venv\lib\site-packages\loguru_handler.py", line 177, in emit
> self._sink.write(str_record)
> File "c:\users\lnz\pycharmprojects\httprunner_study\venv\lib\site-packages\loguru_simple_sinks.py", line 26, in write
> self._stream.write(message)
> File "c:\users\lnz\pycharmprojects\httprunner_study\venv\lib\site-packages\colorama\ansitowin32.py", line 41, in write
> self.__convertor.write(text)
> File "c:\users\lnz\pycharmprojects\httprunner_study\venv\lib\site-packages\colorama\ansitowin32.py", line 162, in write
> self.write_and_convert(text)
> File "c:\users\lnz\pycharmprojects\httprunner_study\venv\lib\site-packages\colorama\ansitowin32.py", line 187, in write_and_convert
> self.write_plain_text(text, cursor, start)
> File "c:\users\lnz\pycharmprojects\httprunner_study\venv\lib\site-packages\colorama\ansitowin32.py", line 196, in write_plain_text
> self.wrapped.flush()
> OSError: [WinError 6] 句柄无效。
> [https://ceshiren.com/uploads/default/original/2X/b/bbde5de5abee6c1a871d5828a97a58fe75b21ce5.png](url)

**Comment by achino520** [comment]
也是这个问题，什么时候解决啊

**Comment by Bu1eCat** [comment]
我出现这个问题，使用

> pip install "httprunner[allure]"

安装后，再次运行，问题解决了。

**Comment by ttsiii** [comment]
提供一个临时解决方案，由群里某个小伙伴提供的！！
原话是：这个好像是因为虚拟环境的问题,   不用虚拟环境就好了

**Comment by ttsiii** [comment]
runner.py -> test_start()-->

拉到最后  if USE_ALLURE:  代码行上加一下

> 
>         import sys
>         logger.remove()
>         log_handler = logger.add(sink=sys.stdout.write, colorize=True)

目前来看是解决了这个问题

**Comment by lee20220110** [comment]
> 解决了吗？我是使用的4.3.0，我添加到这里没有解决问题
![image](https://github.com/httprunner/httprunner/assets/97431426/78de9c17-14be-4ca1-b34e-3da152145266)

**Comment by humiao159** [comment]
没解决呀
