### ISSUE TITLE
在没有外网权限的linux 机器上执行httprunner用例失败

### ISSUE THREAD

**Issue by bdzxhhh** [httprunner/httprunner#1246]
## 问题描述

> 背景：把httprunner和python环境打包成镜像，使用该镜像创建容器，在容器中执行httprunner用例

存在的问题：在拥有外网权限的机器中根据该镜像创建容器，执行httprunner用例是可以的，在没有外网权限的的机器中创建容器，执行httpruner用例后会失败，报错信息如下：

Traceback (most recent call last):
  File "/root/miniconda3/envs/python3.7.9/lib/python3.7/site-packages/urllib3/connection.py", line 170, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "/root/miniconda3/envs/python3.7.9/lib/python3.7/site-packages/urllib3/util/connection.py", line 96, in create_connection
    raise err
  File "/root/miniconda3/envs/python3.7.9/lib/python3.7/site-packages/urllib3/util/connection.py", line 86, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/miniconda3/envs/python3.7.9/lib/python3.7/site-packages/urllib3/connectionpool.py", line 706, in urlopen
    chunked=chunked,
  File "/root/miniconda3/envs/python3.7.9/lib/python3.7/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/root/miniconda3/envs/python3.7.9/lib/python3.7/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "/root/miniconda3/envs/python3.7.9/lib/python3.7/site-packages/urllib3/connection.py", line 353, in connect
    conn = self._new_conn()
  File "/root/miniconda3/envs/python3.7.9/lib/python3.7/site-packages/urllib3/connection.py", line 182, in _new_conn
    self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7fb164771150>: Failed to establish a new connection: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/miniconda3/envs/python3.7.9/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/root/miniconda3/envs/python3.7.9/lib/python3.7/site-packages/urllib3/connectionpool.py", line 756, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/root/miniconda3/envs/python3.7.9/lib/python3.7/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='www.google-analytics.com', port=443): Max retries exceeded with url: /collect (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb164771150>: Failed to establish a new connection: [Errno 110] Connection timed out'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/miniconda3/envs/python3.7.9/bin/hrun", line 8, in <module>
    sys.exit(main_hrun_alias())
  File "/root/miniconda3/envs/python3.7.9/lib/python3.7/site-packages/httprunner/cli.py", line 142, in main_hrun_alias
    main()
  File "/root/miniconda3/envs/python3.7.9/lib/python3.7/site-packages/httprunner/cli.py", line 116, in main
    sys.exit(main_run(extra_args))
  File "/root/miniconda3/envs/python3.7.9/lib/python3.7/site-packages/httprunner/cli.py", line 27, in main_run
    ga_client.track_event("RunAPITests", "hrun")
  File "/root/miniconda3/envs/python3.7.9/lib/python3.7/site-packages/httprunner/utils.py", line 53, in track_event
    self.http_client.post(self.report_url, data=data)
  File "/root/miniconda3/envs/python3.7.9/lib/python3.7/site-packages/requests/sessions.py", line 590, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/root/miniconda3/envs/python3.7.9/lib/python3.7/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/root/miniconda3/envs/python3.7.9/lib/python3.7/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/root/miniconda3/envs/python3.7.9/lib/python3.7/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='www.google-analytics.com', port=443): Max retries exceeded with url: /collect (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb164771150>: Failed to establish a new connection: [Errno 110] Connection timed out'))
Sentry is attempting to send 0 pending error messages
Waiting up to 2 seconds
Press Ctrl-C to quit

## 版本信息

请提供如下版本信息：

 - 操作系统类型: Linux
 - Python 版本: 3.7.9
 - HttpRunner 版本 :3.1.8

## 项目文件内容（非必须）
执行的用例如下：
config:
    name: ***
    variables:
        module: blackbox
        key_name: blackbox_server_url
        Cookie: ${get_cookie_blackbox($module)}
    base_url: ${get_base_url($module, $key_name)}
    verify: false
teststeps:
-   name: ***
    request:
        data: ''
        headers:
            Accept: '*/*'
            Accept-Encoding: gzip, deflate, br
            Connection: keep-alive
            Content-Length: '0'
            Cookie: $Cookie
            User-Agent: PostmanRuntime/7.28.4
        method: POST
        url: ***
    validate:
    -   eq:
        - status_code
        - 200
    -   eq:
        - headers.Content-Type
        - application/json
    -   eq:
        - body.success
        - true

**Comment by debugtalk** [comment]
@bdzxhhh 感谢反馈，该问题将在 3.1.9 中修复
