### ISSUE TITLE
ImportError: cannot import name '_unicodefun' from 'click'

### ISSUE THREAD

**Issue by debugtalk** [httprunner/httprunner#1273]
## Describe the bug

在使用 black 命令时，出现了 `ImportError: cannot import name '_unicodefun' from 'click'` 的异常。

```bash
$ black .
zsh: /usr/local/bin/black: bad interpreter: /usr/local/opt/python/bin/python3.7: no such file or directory
Traceback (most recent call last):
  File "/Users/debugtalk/MyProjects/HttpRunner-dev/httprunner/.venv2/bin/black", line 8, in <module>
    sys.exit(patched_main())
  File "/Users/debugtalk/MyProjects/HttpRunner-dev/httprunner/.venv2/lib/python3.9/site-packages/black.py", line 4134, in patched_main
    patch_click()
  File "/Users/debugtalk/MyProjects/HttpRunner-dev/httprunner/.venv2/lib/python3.9/site-packages/black.py", line 4123, in patch_click
    from click import _unicodefun  # type: ignore
ImportError: cannot import name '_unicodefun' from 'click' (/Users/debugtalk/MyProjects/HttpRunner-dev/httprunner/.venv2/lib/python3.9/site-packages/click/__init__.py)
```

经排查，是 black 的 click 依赖版本的问题。

## Versions

Please complete the following information:

- OS Type: [e.g. macOS]
- Python version: [e.g. 3.9]
- HttpRunner version [e.g. 3.1.10]

**Comment by debugtalk** [comment]
fixed in 3.1.11
