### ISSUE TITLE
生成报告时，工程报错

### ISSUE THREAD

**Issue by ztwo** [HttpRunner/HttpRunner#132]
接口：content_type：multipart/form-data 。参数中需上传file

```python
from requests_toolbelt import MultipartEncoder


def setup_hook_modify(method, url, kwargs):
    data = MultipartEncoder(
        fields={'pro_id': '1', 'main_img': '1', 'sort': '', 'attach_id': '',
                'files[]': ('filename', open('/Users/joko/Desktop/test_data/图片/1.png', 'rb'), 'image/png')}
    )

    kwargs['data'] = data
    kwargs['headers']['content-type'] = data.content_type
```

1：录制出的用例不支持multipart/form-data，利用sethook功能，实现对请求的修改
2：执行->查看请求历史，修改成功

结果：生成报告时，工程报错。报错日志如下

```python
Ran 4 tests in 1.963s

OK
INFO     Start to render Html report ...


Traceback (most recent call last):
  File "/Users/joko/Desktop/test_env39/bin/hrun", line 11, in <module>
    load_entry_point('HttpRunner==1.3.5', 'console_scripts', 'hrun')()
  File "/Users/joko/Desktop/test_env39/lib/python3.6/site-packages/httprunner/cli.py", line 81, in main_hrun
    html_report_template=args.html_report_template
  File "/Users/joko/Desktop/test_env39/lib/python3.6/site-packages/httprunner/task.py", line 232, in run
    html_report_template
  File "/Users/joko/Desktop/test_env39/lib/python3.6/site-packages/httprunner/report.py", line 171, in render_html_report
    rendered_content = Template(template_content).render(summary)
  File "/Users/joko/Desktop/test_env39/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/Users/joko/Desktop/test_env39/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/Users/joko/Desktop/test_env39/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/joko/Desktop/test_env39/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "<template>", line 191, in top-level template code
  File "/Users/joko/Desktop/test_env39/lib/python3.6/site-packages/jinja2/filters.py", line 1078, in do_tojson
    return htmlsafe_json_dumps(value, dumper=dumper, **options)
  File "/Users/joko/Desktop/test_env39/lib/python3.6/site-packages/jinja2/utils.py", line 565, in htmlsafe_json_dumps
    rv = dumper(obj, **kwargs) \
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/encoder.py", line 201, in encode
    chunks = list(chunks)
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/encoder.py", line 430, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/encoder.py", line 404, in _iterencode_dict
    yield from chunks
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/encoder.py", line 437, in _iterencode
    o = _default(o)
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'MultipartEncoder' is not JSON serializable
```

**Comment by debugtalk** [comment]
@ztwo 之前生成报告还没有考虑 MultipartEncoder 的情况，我处理下。

**Comment by debugtalk** [comment]
@ztwo 已经修复了，你更新到 1.3.6 就可以了。

**Comment by ztwo** [comment]
@debugtalk 感谢，修复神速，点赞
