### ISSUE TITLE
yaml转换用例为py格式后的问题

### ISSUE THREAD

**Issue by 406722575** [httprunner/httprunner#1417]
## 问题描述
使用yaml运行用例一切正常，但是转换为py后出现以下问题：
![image](https://user-images.githubusercontent.com/39303693/179147793-f660d88a-bb3d-4c61-b318-e8793de0151f.png)

1、自定义hooks时，变量为$hrp_step_response，报错,KeyError: 'hrp_step_response'
Traceback (most recent call last):
  File "D:\Python310\lib\site-packages\httprunner\parser.py", line 239, in get_mapping_variable
    return variables_mapping[variable_name]
KeyError: 'hrp_step_response'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\HttpRunner4\Projects\fs_first_hospital\testcases\login_testcase_test_test.py", line 59, in <module>
    TestCaseLoginTestcaseTest().test_start()
  File "D:\Python310\lib\site-packages\httprunner\runner.py", line 231, in test_start
    self.__run_step(step)
  File "D:\Python310\lib\site-packages\httprunner\runner.py", line 190, in __run_step
    step_result: StepResult = step.run(self)
  File "D:\Python310\lib\site-packages\httprunner\step.py", line 67, in run
    return self.__step.run(runner)
  File "D:\Python310\lib\site-packages\httprunner\step_request.py", line 348, in run
    return run_step_request(runner, self.__step)
  File "D:\Python310\lib\site-packages\httprunner\step_request.py", line 163, in run_step_request
    call_hooks(runner, step.teardown_hooks, step_variables, "teardown request")
  File "D:\Python310\lib\site-packages\httprunner\step_request.py", line 56, in call_hooks
    runner.parser.parse_data(hook, step_variables)
  File "D:\Python310\lib\site-packages\httprunner\parser.py", line 603, in parse_data
    return parse_data(raw_data, variables_mapping, self.functions_mapping)
  File "D:\Python310\lib\site-packages\httprunner\parser.py", line 415, in parse_data
    return parse_string(raw_data, variables_mapping, functions_mapping)
  File "D:\Python310\lib\site-packages\httprunner\parser.py", line 346, in parse_string
    parsed_args = parse_data(args, variables_mapping, functions_mapping)
  File "D:\Python310\lib\site-packages\httprunner\parser.py", line 418, in parse_data
    return [
  File "D:\Python310\lib\site-packages\httprunner\parser.py", line 419, in <listcomp>
    parse_data(item, variables_mapping, functions_mapping) for item in raw_data
  File "D:\Python310\lib\site-packages\httprunner\parser.py", line 415, in parse_data
    return parse_string(raw_data, variables_mapping, functions_mapping)
  File "D:\Python310\lib\site-packages\httprunner\parser.py", line 375, in parse_string
    var_value = get_mapping_variable(var_name, variables_mapping)
  File "D:\Python310\lib\site-packages\httprunner\parser.py", line 241, in get_mapping_variable
    raise exceptions.VariableNotFound(
httprunner.exceptions.VariableNotFound: hrp_step_response not found in {'password': 'f@6618', 'username': 'aaadmin', 'request': {'params': {}, 'data': None, 'cookies': {}, 'timeout': 120, 'allow_redirects': True, 'verify': False, 'headers': {'HRUN-Request-ID': 'HRUN-9de5cde9-6964-4843-8b09-1ad08d1d177b-323291'}, 'json': None}, 'response': <httprunner.response.ResponseObject object at 0x000002930F057940>}

2、将变量修改为response后，运行py,报TypeError: 'ResponseObject' object is not subscriptable
2022-07-15 12:00:29.852 | INFO     | httprunner.step_request:call_hooks:46 - call hook actions: teardown request
2022-07-15 12:00:29.852 | DEBUG    | httprunner.step_request:call_hooks:55 - call hook function: ${save_token($response)}
2022-07-15 12:00:29.853 | ERROR    | httprunner.parser:parse_string:352 - call function error:
func_name: save_token
args: [<httprunner.response.ResponseObject object at 0x0000011A0AF37940>]
kwargs: {}
TypeError: 'ResponseObject' object is not subscriptable
2022-07-15 12:00:29.853 | INFO     | httprunner.runner:test_start:233 - generate testcase log: D:\HttpRunner4\Projects\fs_first_hospital\logs\7f23a467-9c66-460e-b5bb-f217b230e59c.run.log
Traceback (most recent call last):
  File "D:\HttpRunner4\Projects\fs_first_hospital\testcases\login_testcase_test_test.py", line 59, in <module>
    TestCaseLoginTestcaseTest().test_start()
  File "D:\Python310\lib\site-packages\httprunner\runner.py", line 231, in test_start
    self.__run_step(step)
  File "D:\Python310\lib\site-packages\httprunner\runner.py", line 190, in __run_step
    step_result: StepResult = step.run(self)
  File "D:\Python310\lib\site-packages\httprunner\step.py", line 67, in run
    return self.__step.run(runner)
  File "D:\Python310\lib\site-packages\httprunner\step_request.py", line 348, in run
    return run_step_request(runner, self.__step)
  File "D:\Python310\lib\site-packages\httprunner\step_request.py", line 163, in run_step_request
    call_hooks(runner, step.teardown_hooks, step_variables, "teardown request")
  File "D:\Python310\lib\site-packages\httprunner\step_request.py", line 56, in call_hooks
    runner.parser.parse_data(hook, step_variables)
  File "D:\Python310\lib\site-packages\httprunner\parser.py", line 603, in parse_data
    return parse_data(raw_data, variables_mapping, self.functions_mapping)
  File "D:\Python310\lib\site-packages\httprunner\parser.py", line 415, in parse_data
    return parse_string(raw_data, variables_mapping, functions_mapping)
  File "D:\Python310\lib\site-packages\httprunner\parser.py", line 350, in parse_string
    func_eval_value = func(*parsed_args, **parsed_kwargs)
  File "D:\HttpRunner4\Projects\fs_first_hospital\debugtalk.py", line 53, in save_token
    rep_json = response['cookies']
TypeError: 'ResponseObject' object is not subscriptable

## 版本信息

请提供如下版本信息：

 - 操作系统类型: Windows
 - Python 版本: 3.10.5
 - HttpRunner 版本 4.1.6

## 项目文件内容（非必须）

如果可能，提供项目测试用例文件原始内容可加快 bug 定位和修复速度。

提示：请注意在去除项目敏感信息（IP、账号密码、密钥等）后再进行上传。

**Comment by 406722575** [comment]
3、转换为json，取值时仍会报错
![image](https://user-images.githubusercontent.com/39303693/179165726-a646d383-0923-4751-b549-91106a34e3f6.png)

**Comment by 406722575** [comment]
已解决

**Comment by soonsolidtest** [comment]
> 已解决

请问怎么解决的？
