### ISSUE TITLE
name中使用上一接口extract 变量，工程报错

### ISSUE THREAD

**Issue by ztwo** [HttpRunner/HttpRunner#145]
yaml片段
```yaml
        extract:
        -   user_id: date="">(.*)</span></td>



-   test:
        name: 确认名单-$user_id
        request:
```

报错信息：
```python

Traceback (most recent call last):
  File "/Users/joko/Desktop/test_env41/lib/python3.6/site-packages/httprunner/testcase.py", line 733, in _get_bind_item
    assert self.file_path is not None
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/joko/Desktop/test_env41/bin/hrun", line 11, in <module>
    load_entry_point('HttpRunner==1.3.7', 'console_scripts', 'hrun')()
  File "/Users/joko/Desktop/test_env41/lib/python3.6/site-packages/httprunner/cli.py", line 83, in main_hrun
    html_report_template=args.html_report_template
  File "/Users/joko/Desktop/test_env41/lib/python3.6/site-packages/httprunner/task.py", line 219, in run
    task_suite = TaskSuite(self.path, mapping)
  File "/Users/joko/Desktop/test_env41/lib/python3.6/site-packages/httprunner/task.py", line 178, in __init__
    suite = TestSuite(testset, mapping, http_client_session)
  File "/Users/joko/Desktop/test_env41/lib/python3.6/site-packages/httprunner/task.py", line 100, in __init__
    testcase_name = self.testcase_parser.eval_content_with_bindings(testcase_dict["name"])
  File "/Users/joko/Desktop/test_env41/lib/python3.6/site-packages/httprunner/testcase.py", line 875, in eval_content_with_bindings
    content = self._eval_content_variables(content)
  File "/Users/joko/Desktop/test_env41/lib/python3.6/site-packages/httprunner/testcase.py", line 804, in _eval_content_variables
    variable_value = self.get_bind_variable(variable_name)
  File "/Users/joko/Desktop/test_env41/lib/python3.6/site-packages/httprunner/testcase.py", line 743, in get_bind_variable
    return self._get_bind_item("variable", variable_name)
  File "/Users/joko/Desktop/test_env41/lib/python3.6/site-packages/httprunner/testcase.py", line 737, in _get_bind_item
    "{} is not defined in bind {}s!".format(item_name, item_type))
httprunner.exception.ParamsError: user_id is not defined in bind variables!

```
问题描述：看到报错信息了，但实际使用中需要动态修改用例名称，例如加入user_id。便于报错后排查问题。请问可支持 name当中引用extract的变量吗？

**Comment by debugtalk** [comment]
@ztwo 暂时不支持。

原因在于，解析 name 发生在 unittest 生成测试用例的环节，此时用例还未运行，因此无法解析出 extract 的内容。

我前几天升级了个 beta 版本，你升级后可以解决报错的问题。

```
$ pip install -U httprunner --pre
```
