### ISSUE TITLE
api接口在json用例中有中文且使用uwsgi托管应用的时候报UnicodeEncodeError

### ISSUE THREAD

**Issue by dispensable** [HttpRunner/HttpRunner#150]
环境: uwsgi + flask + httprunner(1.3.7) + python2.7.12
问题: json用例中含有中文时，使用默认的flask调试服务器运行用例没有问题，但是如果使用uwsgi托管应用的时候，运行含中文的json案例会直接报错。

```python
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 367, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 622, in __protected_call__
    return self.run(*args, **kwargs)
  File "/home/rzrk/ApiTest/apiautotest/celery_utils/celery_task.py", line 40, in normal_task
    result = test.run(**running_settings)
  File "/usr/local/lib/python2.7/dist-packages/httprunner/task.py", line 220, in run
    result = self.runner.run(task_suite)
  File "/usr/lib/python2.7/unittest/runner.py", line 158, in run
    result.printErrors()
  File "/usr/lib/python2.7/unittest/runner.py", line 108, in printErrors
    self.printErrorList('ERROR', self.errors)
  File "/usr/lib/python2.7/unittest/runner.py", line 114, in printErrorList
    self.stream.writeln("%s: %s" % (flavour,self.getDescription(test)))
  File "/usr/lib/python2.7/unittest/runner.py", line 24, in writeln
    self.write(arg)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 56-60: ordinal not in range(128)
```

我怀疑和 [这个bug](https://bugs.python.org/issue10417) 有关。但是目前还没找到可行的解决办法，只有把用例里的中文注解删除掉了。

吐槽： py2快点过气吧

**Comment by dispensable** [comment]
找到解决方法了，把默认的ascii的编码方式换到utf8
```shell
PYTHONIOENCODING='UTF-8' uwsgi your_uwsgi_ini_file.ini
```
