### ISSUE TITLE
默认的报告模板response_time_ms有时获取不到

### ISSUE THREAD

**Issue by dispensable** [HttpRunner/HttpRunner#156]
默认模板的`record.response_time_ms`不是所有的记录中都有，有时record中对应的变量是没有`ms`的`reponse_time`。

会导致:

```py
Traceback (most recent call last):
  File "/home/rzrk/ApiTest/venv/local/lib/python2.7/site-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/rzrk/ApiTest/venv/local/lib/python2.7/site-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/home/rzrk/ApiTest/venv/local/lib/python2.7/site-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/rzrk/ApiTest/venv/local/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/rzrk/ApiTest/venv/local/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/rzrk/ApiTest/venv/local/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/rzrk/ApiTest/venv/local/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/rzrk/ApiTest/venv/local/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "./apiautotest/main/views.py", line 246, in report
    return render_template('default_report_template.html', **record)
  File "/home/rzrk/ApiTest/venv/local/lib/python2.7/site-packages/flask/templating.py", line 134, in render_template
    context, ctx.app)
  File "/home/rzrk/ApiTest/venv/local/lib/python2.7/site-packages/flask/templating.py", line 116, in _render
    rv = template.render(context)
  File "/home/rzrk/ApiTest/venv/local/lib/python2.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/rzrk/ApiTest/venv/local/lib/python2.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/rzrk/ApiTest/apiautotest/templates/default_report_template.html", line 183, in top-level template code
    <td style="text-align:center;width:6em;">{{ '%0.1f'| format(record.response_time_ms|float) }} ms</td>
  File "/home/rzrk/ApiTest/venv/local/lib/python2.7/site-packages/jinja2/filters.py", line 668, in do_float
    return float(value)
jinja2.exceptions.UndefinedError: 'dict object' has no attribute 'response_time_ms'
```

此处：
```html
<td style="text-align:center;width:6em;">{{ '%0.1f'| format(record.response_time_ms|float) }} ms</td>
```
可以修改为:
```html
{% if "response_time" in record %}
     <td style="text-align:center;width:6em;">{{ '%0.1f'| format(record.response_time|float) }} ms</td>
{% else %}
     <td style="text-align:center;width:6em;">{{ '%0.1f'| format(record.response_time_ms|float) }} ms</td>
{% endif %}
```

或者在python api中返回结果时统一该字段名为 `response_time_ms`。

**Comment by debugtalk** [comment]
@dispensable 我搜了下代码，并没有 response_time 字段啊。

**Comment by dispensable** [comment]
@debugtalk 0.9.5版本的是`response_time`，后来是`response_time_ms`，以前的测试结果想重新渲染的话就显示不了了（字段不同）。如果当时就生成了html就没这个字段问题。所以修改下的话兼容性更好一点，尤其是对使用api的人来说，保存当时的html不现实，更多的是重新渲染吧。
