### ISSUE TITLE
断言 Contains 时如果 checkValue 为 nil 会引起崩溃

### ISSUE THREAD

**Issue by xyzdev-cell** [httprunner/httprunner#1565]
## 问题描述

> 请对 bug 进行简要描述；
validate 的 contains 校验, check 值为nil时直接引起崩溃
如果是 equal 等方法则没有问题

本质上应该是 testify/assert 的 Contains 引起这个报错
可能需要前置判 checkvalue 是否为空

> 尽量附带运行的命令和报错时的堆栈信息
INF quit hashicorp plugin process
2023-03-06T13:46:25.816+0800 [WARN]  grpc-py: plugin failed to exit gracefully
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0xc0005c6e70 addr=0xbda2c0 pc=0xef2bba]

goroutine 1 [running]:
main.main.func1()
        /github/workspace/hrp/cmd/cli/main.go:19 +0x74
panic({0x11acee0, 0x1c063d0})
        /usr/local/go/src/runtime/panic.go:884 +0x212
github.com/stretchr/testify/assert.includeElement({0x0?, 0x0?}, {0x1143c00?, 0xc00058e430})
        /go/pkg/mod/github.com/stretchr/testify@v1.7.0/assert/assertions.go:724 +0x13a
github.com/stretchr/testify/assert.Contains({0x1438c80, 0xc0001031e0}, {0x0, 0x0}, {0x1143c00, 0xc00058e430}, {0x0, 0x0, 0x0})
        /go/pkg/mod/github.com/stretchr/testify@v1.7.0/assert/assertions.go:767 +0xa8
github.com/httprunner/httprunner/v4/hrp.(*responseObject).Validate(0xc000232200, {0xc0000a0f00?, 0x2, 0x11?}, 0xc0003c5500?)
        /github/workspace/hrp/response.go:197 +0x34c
github.com/httprunner/httprunner/v4/hrp.runStepRequest(0xc0002947d0, 0xc000235ba0)
        /github/workspace/hrp/step_request.go:446 +0xcab
github.com/httprunner/httprunner/v4/hrp.(*StepRequestWithOptionalArgs).Run(0xc00042e420?, 0x12caaf3?)
        /github/workspace/hrp/step_request.go:874 +0x25
github.com/httprunner/httprunner/v4/hrp.(*SessionRunner).Start(0xc0002947d0, 0xc000120a80?)
        /github/workspace/hrp/session.go:77 +0x30e
github.com/httprunner/httprunner/v4/hrp.(*HRPRunner).Run(0xc000118b80, {0xc0001158e0, 0x1, 0x1})
        /github/workspace/hrp/runner.go:210 +0x75d
github.com/httprunner/httprunner/v4/hrp/cmd.glob..func24(0x1c150e0?, {0xc000388870?, 0x1?, 0x3?})
        /github/workspace/hrp/cmd/run.go:30 +0x73
github.com/spf13/cobra.(*Command).execute(0x1c150e0, {0xc0000360c0, 0x3, 0x3})
        /go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:860 +0x663
github.com/spf13/cobra.(*Command).ExecuteC(0x1c15fe0)
        /go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:974 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
        /go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:902
github.com/httprunner/httprunner/v4/hrp/cmd.Execute()
        /github/workspace/hrp/cmd/root.go:62 +0xe7
main.main()
        /github/workspace/hrp/cmd/cli/main.go:23 +0x3b

## 版本信息

请提供如下版本信息：

 - 操作系统类型: [Linux]
 - Python 版本: [3.8.10]
 - Go 版本: [1.20]
 - HttpRunner 版本 [4.2]

**Comment by xyzdev-cell** [comment]
新版本不再出现
