### ISSUE TITLE
性能测试-官方提供的gotest的示例支行就大量报错，没crash

### ISSUE THREAD

**Issue by zhengwh** [httprunner/httprunner#1578]
## 问题描述

> 请对 bug 进行简要描述；

1. 使用官网的文档的gotest代码。https://httprunner.com/docs/user-guide/load-test/concepts/
```
package tests

import (
   "testing"
   "time"

   "github.com/httprunner/httprunner/v4/hrp"
)

func TestLoadTestDemo(t *testing.T) {
   testcase1 := &hrp.TestCase{
      Config: hrp.NewConfig("Load Test Demo").
         SetBaseURL("http://httpbin.org").
         SetThinkTime(
            "random_percentage",
            map[string]float64{"min_percentage": 1, "max_percentage": 1.5},
            4),
      TestSteps: []hrp.IStep{
         hrp.NewStep("transation 1 start").
            StartTransaction("trans1"),
         hrp.NewStep("headers").
            GET("/headers").
            Validate().
            AssertEqual("status_code", 200, "check status code").
            AssertEqual("headers.\"Content-Type\"", "application/json", "check http response Content-Type"),
         hrp.NewStep("transation 1 end").
            EndTransaction("trans1"),
         hrp.NewStep("think time1").
            SetThinkTime(3),
         hrp.NewStep("user-agent").
            GET("/user-agent").
            Validate().
            AssertEqual("status_code", 200, "check status code").
            AssertEqual("headers.\"Content-Type\"", "application/json", "check http response Content-Type"),
         hrp.NewStep("rendezvous 1").
            SetRendezvous("rend1").
            WithUserPercent(0.8).
            WithTimeout(3000),
         hrp.NewStep("TestCaseRef").
            CallRefCase(&hrp.TestCase{Config: hrp.NewConfig("TestCase2")}),
      },
   }

   b := hrp.NewStandaloneBoomer(1000, 100) //spawn_count: 1000, spawn_rate: 100
   go b.Run(testcase1)
   time.Sleep(1000 * time.Second) //expected running time
   b.Quit()
}
```

运行中途会大量报错：
```
goroutine 6007 [running]:
runtime/debug.Stack()
	/Users/g/.goenv/versions/1.19.3/src/runtime/debug/stack.go:24 +0x7a
github.com/httprunner/httprunner/v4/hrp/pkg/boomer.(*runner).safeRun.func1()
	/Users/g/go/1.19.3/pkg/mod/github.com/httprunner/httprunner/v4@v4.3.1/hrp/pkg/boomer/runner.go:271 +0x4f
panic({0x100ed0700, 0xc000d4e780})
	/Users/g/.goenv/versions/1.19.3/src/runtime/panic.go:890 +0x267
github.com/httprunner/httprunner/v4/hrp.(*StepTestCaseWithOptionalArgs).Run(0xc0000146c8, 0xc00122de00)
	/Users/g/go/1.19.3/pkg/mod/github.com/httprunner/httprunner/v4@v4.3.1/hrp/step_testcase.go:69 +0xb59
github.com/httprunner/httprunner/v4/hrp.(*HRPBoomer).convertBoomerTask.func2()
	/Users/g/go/1.19.3/pkg/mod/github.com/httprunner/httprunner/v4@v4.3.1/hrp/boomer.go:377 +0x5b3
github.com/httprunner/httprunner/v4/hrp/pkg/boomer.(*runner).safeRun(0xc0002b4400, 0xc000347180)
	/Users/g/go/1.19.3/pkg/mod/github.com/httprunner/httprunner/v4@v4.3.1/hrp/pkg/boomer/runner.go:278 +0x44
github.com/httprunner/httprunner/v4/hrp/pkg/boomer.(*runner).spawnWorkers.func1()
	/Users/g/go/1.19.3/pkg/mod/github.com/httprunner/httprunner/v4@v4.3.1/hrp/pkg/boomer/runner.go:445 +0x170
github.com/httprunner/httprunner/v4/hrp/pkg/boomer.(*runner).goAttach.func1()
	/Users/g/go/1.19.3/pkg/mod/github.com/httprunner/httprunner/v4@v4.3.1/hrp/pkg/boomer/runner.go:504 +0x95
created by github.com/httprunner/httprunner/v4/hrp/pkg/boomer.(*runner).goAttach
	/Users/g/go/1.19.3/pkg/mod/github.com/httprunner/httprunner/v4@v4.3.1/hrp/pkg/boomer/runner.go:502 +0x1c6
{"level":"info","time":3,"time":"2023-03-30T08:44:35+08:00","message":"think time"}
interface conversion: interface {} is *hrp.TCase, not *hrp.TestCase

```

> 尽量附带运行的命令和报错时的堆栈信息

## 版本信息

- macOs
- go 1.19.3
- github.com/httprunner/httprunner/v4 v4.3.1

## 项目文件内容（非必须）

如果可能，提供项目测试用例文件原始内容可加快 bug 定位和修复速度。

提示：请注意在去除项目敏感信息（IP、账号密码、密钥等）后再进行上传。

**Comment by ywanbing** [comment]
这个问题已经确认，是由于 (*StepRendezvous).Run 里面的执行 (*TestCase).ToTCase() 所引起的。

```golang
func (tc *TestCase) ToTCase() *TCase {
	tCase := &TCase{
		Config: tc.Config,
	}
	for _, step := range tc.TestSteps {
		if step.Type() == stepTypeTestCase {
			if testcase, ok := step.Struct().TestCase.(*TestCase); ok {
                                // 如果存在文件引用，那么这个递归就会改掉原来的值
				step.Struct().TestCase = testcase.ToTCase()
			}
		}
		tCase.TestSteps = append(tCase.TestSteps, step.Struct())
	}
	return tCase
}
```

我觉得这个方法应该类似 Clone，不能去影响原来的值。
