### ISSUE TITLE
框架不兼容响应body中含有中文的场景

### ISSUE THREAD

**Issue by smigoYu** [HttpRunner/HttpRunner#228]
![image](https://user-images.githubusercontent.com/8230325/40036404-dd32a9a2-5839-11e8-9a11-3dd6205ff389.png)

Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\httprunner\task.py", line 26, in runTest
    self.test_runner.run_test(self.testcase_dict)
  File "C:\Python27\lib\site-packages\httprunner\runner.py", line 210, in run_test
    err_resp_msg += "body: {}\n".format(resp.text)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 21-23: ordinal not in range(128)

**Comment by debugtalk** [comment]
This bug has been fixed in 1.5.X.
