### ISSUE TITLE
parameters的csv中包含中文时出现UnicodeDecodeError

### ISSUE THREAD

**Issue by lukcyjane** [httprunner/httprunner#243]
使用parameters指定参数列表，当csv中含有中文时，报错如下：

```
Traceback (most recent call last):
  File "C:\Python36\Scripts\hrun-script.py", line 11, in <module>
    load_entry_point('HttpRunner==1.4.4', 'console_scripts', 'hrun')()
  File "c:\python36\lib\site-packages\httprunner\cli.py", line 82, in main_hrun
    runner = HttpRunner(failfast=args.failfast, dot_env_path=args.dot_env_path).run(args.testset_paths)
  File "c:\python36\lib\site-packages\httprunner\task.py", line 242, in run
    task_suite = init_task_suite(path_or_testsets, mapping)
  File "c:\python36\lib\site-packages\httprunner\task.py", line 206, in init_task_suite
    return TaskSuite(testsets, mapping, http_client_session)
  File "c:\python36\lib\site-packages\httprunner\task.py", line 187, in __init__
    suite = TestSuite(testset, mapping, http_client_session)
  File "c:\python36\lib\site-packages\httprunner\task.py", line 76, in __init__
    config_dict_parameters
  File "c:\python36\lib\site-packages\httprunner\task.py", line 116, in _get_parametered_variables
    self.testset_file_path
  File "c:\python36\lib\site-packages\httprunner\testcase.py", line 712, in parse_parameters
    parsed_parameter_content = testcase_parser.eval_content_with_bindings(parameter_content)
  File "c:\python36\lib\site-packages\httprunner\testcase.py", line 915, in eval_content_with_bindings
    content = self._eval_content_functions(content)
  File "c:\python36\lib\site-packages\httprunner\testcase.py", line 813, in _eval_content_functions
    eval_value = self.parameterize(*args, **kwargs)
  File "c:\python36\lib\site-packages\httprunner\testcase.py", line 794, in parameterize
    csv_content_list = FileUtils.load_file(parameter_file_path)
  File "c:\python36\lib\site-packages\httprunner\utils.py", line 128, in load_file
    return FileUtils._load_csv_file(file_path)
  File "c:\python36\lib\site-packages\httprunner\utils.py", line 112, in _load_csv_file
    for row in reader:
  File "c:\python36\lib\csv.py", line 111, in __next__
    self.fieldnames
  File "c:\python36\lib\csv.py", line 98, in fieldnames
    self._fieldnames = next(self.reader)
  File "c:\python36\lib\codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd6 in position 76: invalid continuation byte
'utf-8' codec can't decode byte 0xd6 in position 76: invalid continuation byte
```

**Comment by debugtalk** [comment]
@lukcyjane 我本地试了下，在 Python 3 下面都是正常的，只有在 2.7 中会出现 UnicodeDecodeError。
你可否将你的脚本数据发出来看下，我再排查下。

**Comment by rotateX** [comment]
我也出现这个问题，parameters从csv文件中读取，csv中的参数值是中文的时候报错，UnicodeDecodeError: 'utf-8' codec can't decode byte 0xcf in position 6: invalid continuation byte

**Comment by yaming116** [comment]
@baoshd @rotateX @lukcyjane 最好提供一下详细的例子，目前测试不出来你们的情况。 测试了python2.7 和3.7的版本


```python
#! /usr/bin/env python
# -*- coding: utf-8 -*-

import csv
import io
import os
import sys


if sys.version_info[0] == 2:
    reload(sys)
    sys.setdefaultencoding('utf-8')


def _load_csv_file(csv_file):
    """ load csv file and check file content format
    @param
        csv_file: csv file path
        e.g. csv file content:
            username,password
            test1,111111
            test2,222222
            test3,333333
    @return
        list of parameter, each parameter is in dict format
        e.g.
        [
            {'username': 'test1', 'password': '111111'},
            {'username': 'test2', 'password': '222222'},
            {'username': 'test3', 'password': '333333'}
        ]
    """
    csv_content_list = []

    with io.open(csv_file, encoding='utf-8') as csvfile:
        reader = csv.DictReader(csvfile)
        for row in reader:
            csv_content_list.append(row)

    return csv_content_list


if __name__ == '__main__':
    csv_path = os.path.abspath('./aa.csv')
    print(_load_csv_file(csv_path))
```

```csv
#aa.csv
1, 测试
2, 测试
```

**Comment by GodXzy** [comment]
比如csv文件配置为：
username,password
嘿嘿嘿,123456
这个时候跑脚本会报编码错误，将中文替换为字母就不会报错；

**Comment by yaming116** [comment]
@GodXzy 试试我上面的测试代码，或者发送你的测试代码上来，因为我测试没有任何错误，环境mac

**Comment by rotateX** [comment]
@yaming116 你试试把username的值改成中文{'username': 'test1', 'password': '111111'}

**Comment by yaming116** [comment]
已经测试数据,

```csv
username,password
嘿嘿嘿,123456
1, 测试
2, 测试
```

```csv
嘿嘿嘿,123456
1, 测试
2, 测试
```

**Comment by GodXzy** [comment]
你好，后面遇到发详细数据给你。

**Comment by rotateX** [comment]
demo_testsuite.yml
```
config:
    name: 天气查询

testcases:
    get city weather:
        testcase: /testcases/demo_testcase.yml
        parameters:
            city: ${P(data/cityname.csv)}
```
demo_testcase.yml
```
- config:
    name: 天气
    base_url: http://wthrcdn.etouch.cn
            
- test:
    name: ${city}天气
    request:
        url: /weather_mini
        method: GET
        params:
            city: $city
    validate:
        - eq: [status_code, 200]
        - eq: [content.desc, "OK"]
        - eq: [content.status, 1000]
```
cityname.csv
![data](https://user-images.githubusercontent.com/13715153/71878341-5f172900-3166-11ea-8cee-1ae54eb711b7.png)

执行：hrun demo_testsuite.yml
结果：UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb1 in position 6: invalid start byte

**Comment by yaming116** [comment]
csv直接复制上来咯，干嘛要弄一个图片

**Comment by rotateX** [comment]
@yaming116  恩 谢谢  我HttpRunner升级到2.5.4 还是报同样的问题，python3.7.4，win10。现在换了个办法处理了，直接自定义一个函数，先读取出来，再引用。
