### ISSUE TITLE
生成报告时，报MemoryError错误

### ISSUE THREAD

**Issue by sunjundi** [httprunner/httprunner#246]
测试用例是put一张图片到服务器，循环了1000次，目前测试如果只循环200次，是没问题的。

debug日志如下

Ran 1000 tests in 369.102s

```
FAILED (errors=432)
INFO     render with html report template: html_report_template_nodetail.html
INFO     Start to render Html report ...
Traceback (most recent call last):
  File "c:\users\sengled\appdata\local\programs\python\python36-32\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\sengled\appdata\local\programs\python\python36-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\sengled\AppData\Local\Programs\Python\Python36-32\Scripts\hrun.exe\__main__.py", line 9, in <module>
  File "c:\users\sengled\appdata\local\programs\python\python36-32\lib\site-packages\httprunner\cli.py", line 91, in main_hrun
    html_report_template=args.html_report_template
  File "c:\users\sengled\appdata\local\programs\python\python36-32\lib\site-packages\httprunner\task.py", line 260, in gen_html_report
    html_report_template
  File "c:\users\sengled\appdata\local\programs\python\python36-32\lib\site-packages\httprunner\report.py", line 78, in render_html_report
    logger.log_debug("render data: {}".format(summary))
MemoryError
```

**Comment by debugtalk** [comment]
@sunjundi 循环1000次，看你的堆栈日志，失败是在生成报告的环节？如果不生成报告的话是否正常？

**Comment by huaqiaoni** [comment]
我也遇到这个报错，运行都正常，就是生成报告报memory error，是因为读取的CSV文件的数据有70多行（40多行是正常的，40多行的测试步骤大概2000多），里面的测试步骤比较多。我怀疑是读取文件那里内存溢出，但是不知道要怎么修改？请问你这个问题解决了吗？
