### ISSUE TITLE
skip对调用suite的用例无效，将是skip放入suite内部则会报错

### ISSUE THREAD

**Issue by wushenghang** [httprunner/httprunner#257]
首先将skip放入调用suite的用例中运行,如：
```
- test:
    name: 注册
    skip: "skip this test unconditionally"
    suite: suite_register($timestamp,$phone,$sms_phone,old_code)
```
则正常运行：
```
获取注册验证码
INFO     POST /sms/register
INFO     status_code: 200, response_time(ms): 1273.29 ms, response_length: 42 bytes

.注册
483866
INFO     POST /user/register

INFO     status_code: 200, response_time(ms): 129.91 ms, response_length: 266 bytes
.
----------------------------------------------------------------------
Ran 2 tests in 3.699s

OK
INFO     Start to render Html report ...
INFO     Generated Html report: D:\003code\gitlab\apitest\reports\2018-05-28-13-20-07.html
```

若是直接在suite中skip：
```
- config:
    def: suite_register($timestamp,$phone,$sms_phone,old_code)
- test:
    name: 获取注册验证码
    skip: "skip this test unconditionally"
    api: api_sms_registerCode_POST($timestamp,$phone)
    validate:
    -   eq: ["content.msg","验证码已经发送"]

- test:
    name: 注册
    skip: "skip this test unconditionally"
    variables:
        sms_code: ${getSmsCode($sms_phone,$old_code)}
        pwd: ${encryptThreeDES(123456)}
    api: api_user_register_POST($timestamp,$sms_code,$pwd,$phone)
    validate:
    -   eq: ["content.status",0]
    -   eq: ["content.msg","请求成功"]
```

则出现以下报错：
```
s获取注册验证码

注册
s
----------------------------------------------------------------------

Ran 2 tests in 0.001s

OK (skipped=2)
INFO     Start to render Html report ...
Traceback (most recent call last):
  File "D:/003code/gitlab/apitest/main-debug.py", line 45, in <module>
    main_hrun()
  File "D:/003code/gitlab/apitest/main-debug.py", line 37, in main_hrun
    html_report_template=argss["html_report_template"]
  File "D:\003code\gitlab\apitest\httprunner\task.py", line 267, in gen_html_report
    html_report_template
  File "D:\003code\gitlab\apitest\httprunner\report.py", line 95, in render_html_report
    stringify_body(meta_data, 'request')
  File "D:\003code\gitlab\apitest\httprunner\report.py", line 110, in stringify_body
    headers = meta_data['{}_headers'.format(request_or_response)]
KeyError: 'request_headers'
```

**Comment by searchbb** [comment]
@debugtalk 这里我有个疑问，我觉得上述在调用suite的地方加skip根本就不会work啊，我看了一下你的代码，你是根绝api或者suite的关键字把读取到的api或者suite的文件里的对应的test case的block，也就是test这一段给替换到实际调用的yml文件里对应的block里面，所以只有写在被调用处的skip才会被读取到，执行到，写在调用处的skip根本就会被忽略吧


<img width="1096" alt="image" src="https://user-images.githubusercontent.com/42245656/44016440-90af5d36-9f07-11e8-80b3-31f45a6ce830.png">

**Comment by gqq112** [comment]
同问，suite如果跳过

**Comment by wushenghang** [comment]
吴升航收到你的来信，我会尽快回复
