### ISSUE TITLE
httprunner.exception.SuiteNotFound

### ISSUE THREAD

**Issue by lzclff** [HttpRunner/HttpRunner#277]
环境检查过都没有问题，但是运行 yaml脚本的时候均提示错误，开发者模式调试的unittest脚本运行没有问题

```
[root@hzzh-test-13 testcases]# hrun smoketest.yml 
Traceback (most recent call last):
  File "/usr/bin/hrun", line 11, in <module>
    sys.exit(main_hrun())
  File "/opt/python3/lib/python3.6/site-packages/httprunner/cli.py", line 82, in main_hrun
    runner = HttpRunner(failfast=args.failfast, dot_env_path=args.dot_env_path).run(args.testset_paths)
  File "/opt/python3/lib/python3.6/site-packages/httprunner/task.py", line 243, in run
    task_suite = init_task_suite(path_or_testsets, mapping)
  File "/opt/python3/lib/python3.6/site-packages/httprunner/task.py", line 201, in init_task_suite
    testsets = TestcaseLoader.load_testsets_by_path(path_or_testsets)
  File "/opt/python3/lib/python3.6/site-packages/httprunner/testcase.py", line 362, in load_testsets_by_path
    testset = TestcaseLoader.load_testsets_by_path(file_path)
  File "/opt/python3/lib/python3.6/site-packages/httprunner/testcase.py", line 381, in load_testsets_by_path
    testset = TestcaseLoader.load_test_file(path)
  File "/opt/python3/lib/python3.6/site-packages/httprunner/testcase.py", line 241, in load_test_file
    block = TestcaseLoader._get_block_by_name(ref_call, "suite")
  File "/opt/python3/lib/python3.6/site-packages/httprunner/testcase.py", line 263, in _get_block_by_name
    block = TestcaseLoader._get_test_definition(func_name, ref_type)
  File "/opt/python3/lib/python3.6/site-packages/httprunner/testcase.py", line 298, in _get_test_definition
    raise exception.SuiteNotFound(err_msg)
httprunner.exception.SuiteNotFound: setup_and_reset not found!
```

请问这是什么原因

**Comment by debugtalk** [comment]
运行测试时依赖于目录路径，需要在项目根目录执行测试，与 tests 目录同级。
