### ISSUE TITLE
Traceback (most recent call last)

### ISSUE THREAD

**Issue by Chrisxi0318** [HttpRunner/HttpRunner#302]
I get error when run hrun:

Traceback (most recent call last):
  File "/usr/local/bin/hrun", line 7, in <module>
    from httprunner.cli import main_hrun
  File "/usr/local/lib/python2.7/dist-packages/httprunner/__init__.py", line 3, in <module>
    from httprunner.task import HttpRunner
  File "/usr/local/lib/python2.7/dist-packages/httprunner/task.py", line 7, in <module>
    from httprunner import exception, logger, runner, testcase, utils
  File "/usr/local/lib/python2.7/dist-packages/httprunner/runner.py", line 6, in <module>
    from httprunner.client import HttpSession
  File "/usr/local/lib/python2.7/dist-packages/httprunner/client.py", line 14, in <module>
    urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)
AttributeError: 'module' object has no attribute 'disable_warnings'

Anybody know why?Thanks

**Comment by debugtalk** [comment]
@Chrisxi0318 try this first in your command.

```
✗ python
Python 2.7.14 (default, May 31 2018, 14:38:28)
[GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import urllib3
>>> urllib3.disable_warnings
<function disable_warnings at 0x101281398>
>>>
```

Is there the same error occurred before?
