### ISSUE TITLE
config 中引用 default_request 出现 AttributeError

### ISSUE THREAD

**Issue by grizz622** [HttpRunner/HttpRunner#309]
文件：login.yml

```
- config:
    name: "mt_login"
    variables:
        - _from: 'ios'
    request: $default_request
```

文件：debugtalk.py

```
default_request = {
    "base_url": "http://api.mengtuiapp.com",
    "headers":{
        "content-type": "application/json"
        }
}
```

接口运行成功，但是有Traceback，如下：

```
Ran 3 tests in 0.103s

OK
Traceback (most recent call last):
  File "/usr/local/bin/hrun", line 11, in <module>
    sys.exit(main_hrun())
  File "/usr/local/lib/python2.7/site-packages/httprunner/cli.py", line 81, in main_hrun
    runner = HttpRunner(failfast=args.failfast, dot_env_path=args.dot_env_path).run(args.testset_paths)
  File "/usr/local/lib/python2.7/site-packages/httprunner/task.py", line 269, in run
    test_suite_summary["base_url"] = test_suite.config.get("request", {}).get("base_url", "")
AttributeError: 'str' object has no attribute 'get'
```

**Comment by jeremy8250** [comment]
我也有同样的问题，我的py是3.6.4的

**Comment by BensonMax** [comment]
@jeremy8250  后面解决了吗？降级python 有没有用？

**Comment by BensonMax** [comment]
亲测1.4.4 可以

**Comment by jeremy8250** [comment]
@BensonMax ,我回到1.4.6就好用了

**Comment by debugtalk** [comment]
已修复，最新版本 1.5.11。
