### ISSUE TITLE
locusts命令传入host参数无效

### ISSUE THREAD

**Issue by yileye** [HttpRunner/HttpRunner#35]
```text
使用场景
1.并发总数300
2.每秒并发30
```
这种情况下，框架会抛出一个异常
```text
[2017-08-29 11:13:55,555] yileyedeMacBook-Pro.local/ERROR/stderr: Traceback (most recent call last):
  File "/Users/finup/gitlab/ApiTestEngine/env/src/locustio/locust/core.py", line 267, in run
    self.execute_next_task()
  File "/Users/finup/gitlab/ApiTestEngine/env/src/locustio/locust/core.py", line 293, in execute_next_task
    self.execute_task(task["callable"], *task["args"], **task["kwargs"])
  File "/Users/finup/gitlab/ApiTestEngine/env/src/locustio/locust/core.py", line 305, in execute_task
    task(self, *args, **kwargs)
  File "/Users/finup/gitlab/ApiTestEngine/locustfile.py", line 15, in test_specified_scenario
    self.test_runner.run_testset(self.testset)
  File "/Users/finup/gitlab/ApiTestEngine/ate/runner.py", line 142, in run_testset
    result = self.run_test(testcase)
  File "/Users/finup/gitlab/ApiTestEngine/ate/runner.py", line 97, in run_test
    resp = self.http_client_session.request(url=url, method=method, **parsed_request)
  File "/Users/finup/gitlab/ApiTestEngine/env/src/locustio/locust/clients.py", line 113, in request
    response = self._send_request_safe_mode(method, url, **kwargs)
  File "/Users/finup/gitlab/ApiTestEngine/env/src/locustio/locust/clients.py", line 157, in _send_request_safe_mode
    return requests.Session.request(self, method, url, **kwargs)
  File "/Users/finup/gitlab/ApiTestEngine/env/lib/python3.6/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/finup/gitlab/ApiTestEngine/env/lib/python3.6/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/Users/finup/gitlab/ApiTestEngine/env/lib/python3.6/site-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/Users/finup/gitlab/ApiTestEngine/env/lib/python3.6/site-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/Users/finup/gitlab/ApiTestEngine/env/lib/python3.6/site-packages/urllib3/connectionpool.py", line 346, in _make_request
    self._validate_conn(conn)
  File "/Users/finup/gitlab/ApiTestEngine/env/lib/python3.6/site-packages/urllib3/connectionpool.py", line 850, in _validate_conn
    conn.connect()
  File "/Users/finup/gitlab/ApiTestEngine/env/lib/python3.6/site-packages/urllib3/connection.py", line 314, in connect
    cert_reqs=resolve_cert_reqs(self.cert_reqs),
  File "/Users/finup/gitlab/ApiTestEngine/env/lib/python3.6/site-packages/urllib3/util/ssl_.py", line 269, in create_urllib3_context
    context.options |= options
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 459, in options
    super(SSLContext, SSLContext).options.__set__(self, value)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 459, in options
    super(SSLContext, SSLContext).options.__set__(self, value)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 459, in options
    super(SSLContext, SSLContext).options.__set__(self, value)
  [Previous line repeated 314 more times]
RecursionError: maximum recursion depth exceeded
```

```text
单独使用locust框架没还没遇到这个问题，我还在看源码追查问题出在什么地方，稍后如果发现在comment上来
```

**Comment by yileye** [comment]
问题已经解决，问题如下：
```text
def gen_locustfile(testcase_file_path):
    """ generate locustfile from template.
    """
    locustfile_path = 'locustfile.py'
    with codecs.open('ate/locustfile_template', encoding='utf-8') as template:
        with codecs.open(locustfile_path, 'w', encoding='utf-8') as locustfile:
            template_content = template.read()
            template_content = template_content.replace("$HOST", "https://skypixel.com")
            template_content = template_content.replace("$TESTCASE_FILE", testcase_file_path)
            locustfile.write(template_content)

    return locustfile_path
```
```text
host没有根据用例中的host的动态传入
```

**Comment by debugtalk** [comment]
@yileye 是这样的，因为`YAML/JSON`接口测试用例中，我们已经都有了host信息，因此在采用Locust执行测试的时候，其实是不需要再传入HOST的。只是Locust脚本中，又必须要填一个host，所以当时就搞了个作为占位符。

**Comment by debugtalk** [comment]
拟打算修复为如下形式：
- locusts 命令支持传入 `--host/-H` 参数；
- 若传入该参数，该参数将覆盖`YAML/JSON`测试用例中的`base_url`；
- 若不传入该参数，就将读取`YAML/JSON`测试用例中的`base_url`，作为`locustfile.py`的host参数。

**Comment by yileye** [comment]
@debugtalk 好的，这样的话能避免使用当中出现的一些不必要的异常，Locust有web和no web两种模式，是否都支持，因为想跑在跑接口的时候自动跑一些性能测试的东西

**Comment by debugtalk** [comment]
@yileye `web`和`no-web`都是支持的；总的来说，使用`locusts`命令相比于原生的`locust`命令，功能没有删减，`locust`命令能用的`locusts`都能用。
