### ISSUE TITLE
suite/testsuites目录问题

### ISSUE THREAD

**Issue by coreywei** [HttpRunner/HttpRunner#387]
## 问题描述

1. 用hrun --startproject 新建项目，有api/testsuites/testcases和其它目录
2. 使用测试用例分层，创建相关的api，模块，用例，并把它们分别放在上述三个目录里
3. hrun testcases/test.json，报错，找不到相关suite的定义
4. 把testsuites目录改名为suite，重跑，居然可以跑过。很困惑，自带的--startproject有问题？看源码中的tests目录也是用suite目录，搞不懂为什么--startproject会建testsuites目录。如果是重构中，为什么没有配套重构其它内容。。。

## 版本信息

请提供如下版本信息：

 - 操作系统类型: macos
 - Python 版本 3.6
 - HttpRunner 版本 1.5.13

## 堆栈信息
$ hrun testcases/test_suite.pretty.json 
INFO     Loading environment variables from /Users/cwei/Documents/workspace/lambda/.env
ERROR    !!!!!!!!!! exception stage: load tests !!!!!!!!!!
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/bin/hrun", line 11, in <module>
    sys.exit(main_hrun())
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/httprunner/cli.py", line 86, in main_hrun
    runner.run(args.testset_paths)
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/httprunner/api.py", line 325, in run
    testcases_list = self.load_tests(path_or_testcases)
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/httprunner/api.py", line 100, in load_tests
    testcases = loader.load_testcases(path_or_testcases)
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/httprunner/loader.py", line 939, in load_testcases
    testcases = load_testcases(file_path)
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/httprunner/loader.py", line 965, in load_testcases
    testcase = _load_test_file(path)
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/httprunner/loader.py", line 419, in _load_test_file
    block = _get_block_by_name(ref_call, "def-testcase")
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/httprunner/loader.py", line 456, in _get_block_by_name
    block = _get_test_definition(func_name, ref_type)
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/httprunner/loader.py", line 502, in _get_test_definition
    raise exceptions.TestcaseNotFound(err_msg)
httprunner.exceptions.TestcaseNotFound: login not found!

**Comment by debugtalk** [comment]
@coreywei 这里存在一个历史问题。
之前采用 suite 目录存储测试用例，用于在测试场景中进行组装形成更大的测试场景。
在近期的重构中，重新梳理了相应的概念。当前对脚手架功能进行了调整，但在程序中的读取测试用例的逻辑还没有完成调整，主要是考虑到兼容性问题，这块儿计划在 1.6 版本中完成。

最新的概念描述文档：http://cn.httprunner.org/concept/project-structure/

**Comment by coreywei** [comment]
@debugtalk 
还真不知道这段历史。所以 http://debugtalk.com/post/HttpRunner-testcase-layer/ 里面描述的东西已经不适用当前版本的httprunner了是吗？

看了最近更新的 http://cn.httprunner.org/concept/project-structure/ 和 http://cn.httprunner.org/concept/testcase-structure/ ，就更难理解了：
```
测试用例集（testsuite）：对应一个文件夹，包含单个或多个测试用例（YAML/JSON）文件
测试用例（testcase）：对应一个 YAML/JSON 文件，包含单个或多个测试步骤
测试步骤（teststep）：对应 YAML/JSON 文件中的一个 test，描述单次接口测试的全部内容，包括发起接口请求、解析响应结果、校验结果等
```

以上的三个概念，如何跟api/testcases/testsuites目录联系起来？每层的文档结构是如何，在哪里能看到符合正确概念的测试用例分层的example? 感觉以前api/suite/testcase还好理解。

**Comment by coreywei** [comment]
特别是testsuites更诡异，只是对应一个文件夹， 包含testcase文件？可是testcase文件，不是应该放在testcases目录下面吗

**Comment by coreywei** [comment]
@debugtalk 这个demo目录的相关文件能否发出来参考一下？

demo
├── .env
├── api
│   └── user.yml
├── debugtalk.py
├── reports
│   └── 1535713039.html
├── testcases
│   ├── login.yml
│   └── logout.yml
└── testsuites
    └── login_and_logout.yml

**Comment by zhangjiukun** [comment]
卡在这里了，总是报错
INFO     Loading environment variables from /home/demo/.env
INFO     Loading environment variables from /home/demo/.env
ERROR    !!!!!!!!!! exception stage: load tests !!!!!!!!!!
httprunner.exceptions.FunctionNotFound: login_logout($username, ${get_encrypt_password()}) not found!

├── .env
├── api
│   └── base.yml
├── data
├── debugtalk.py
├── logout.yml
├── newreport.bat
├── reports
├── run.py
├── suite
│   └── create_and_get.yml
├── testcases
│   └── smoketest.yml
└── testsuites
    ├── 001.json
    └── create_and_get.yml
我都不知道该怎么放了

**Comment by zhangjiukun** [comment]
我改成suit也跑不过，找不到suit定义的方法

**Comment by coreywei** [comment]
@debugtalk 是否有符合最新目录规范的（api/testcases/testsuites）、能够运行的例子参考一下？

**Comment by debugtalk** [comment]
测试用例分层机制已补充文档：
https://cn.httprunner.org/advanced/testcase-layer/
