### ISSUE TITLE
--dot-env-path 不起作用

### ISSUE THREAD

**Issue by coreywei** [httprunner/httprunner#391]
运行时用--dot-env-path指定env文件并不起作用，每次都去读取项目根目录下的.env文件
```
$ hrun api/login.pretty.json --dot-env-path 1.env --log-level debug
INFO     Loading environment variables from /Users/cwei/Documents/workspace/xxx/httprunner/demo/lambda/.env
```

1.5.13

@debugtalk

**Comment by debugtalk** [comment]
@coreywei 这个参数中途有去掉过，后面又加回来了。

你升级到最新版再试下： pip install -U git+https://github.com/HttpRunner/HttpRunner.git

**Comment by coreywei** [comment]
升级了最新版还是不行

$ hrun testcases/test_suite.pretty.json --dot-env-path 1.env --log-level DEBUG
DEBUG    .env file not exist in: /Users/cwei/Documents/workspace/xxx/httprunner/demo/lambda
ERROR    !!!!!!!!!! exception stage: load tests !!!!!!!!!!
Traceback (most recent call last):
  File "/usr/local/bin/hrun", line 11, in <module>
    sys.exit(main_hrun())
  File "/usr/local/lib/python3.6/site-packages/httprunner/cli.py", line 85, in main_hrun
    runner.run(args.testset_paths)
  File "/usr/local/lib/python3.6/site-packages/httprunner/api.py", line 325, in run
    testcases_list = self.load_tests(path_or_testcases)
  File "/usr/local/lib/python3.6/site-packages/httprunner/api.py", line 100, in load_tests
    testcases = loader.load_testcases(path_or_testcases)
  File "/usr/local/lib/python3.6/site-packages/httprunner/loader.py", line 939, in load_testcases
    testcases = load_testcases(file_path)
  File "/usr/local/lib/python3.6/site-packages/httprunner/loader.py", line 955, in load_testcases
    load_project_tests(path)
  File "/usr/local/lib/python3.6/site-packages/httprunner/loader.py", line 910, in load_project_tests
    load_debugtalk_module()
  File "/usr/local/lib/python3.6/site-packages/httprunner/loader.py", line 297, in load_debugtalk_module
    imported_module = importlib.import_module("debugtalk")
  File "/usr/local/Cellar/python/3.6.5_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/cwei/Documents/workspace/nfd-autotest/httprunner/demo/lambda/debugtalk.py", line 3, in <module>
    base_url = os.environ["base_url"]
  File "/usr/local/Cellar/python/3.6.5_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/os.py", line 669, in __getitem__
    raise KeyError(key) from None
KeyError: 'base_url'

**Comment by coreywei** [comment]
理论上在1.5.12就加回去了，我用的是1.5.13，现在升级到最新也是有问题，感觉是个bug?

**Comment by alterlet** [comment]
我也遇到该问题，httprunner的版本是V1.5.15，请 @debugtalk 帮忙看看啊

**Comment by debugtalk** [comment]
fixed.

**Comment by qiujianzhong** [comment]
V4  不支持吗？
