### ISSUE TITLE
1.5.13版本 variable为list或者map类型的时候，生成报告就会报错

### ISSUE THREAD

**Issue by shaoshao613** [httprunner/httprunner#405]
```
ERROR    !!!!!!!!!! exception stage: aggregate results !!!!!!!!!!
Traceback (most recent call last):
  File "/Users/ting.shao1/Documents/python_ven_hrun/bin/hrun", line 11, in <module>
    sys.exit(main_hrun())
  File "/Users/ting.shao1/Documents/python_ven_hrun/lib/python3.6/site-packages/httprunner/cli.py", line 86, in main_hrun
    runner.run(args.testset_paths)
  File "/Users/ting.shao1/Documents/python_ven_hrun/lib/python3.6/site-packages/httprunner/api.py", line 337, in run
    self.aggregate(results)
  File "/Users/ting.shao1/Documents/python_ven_hrun/lib/python3.6/site-packages/httprunner/api.py", line 294, in aggregate
    utils.print_io(in_out)
  File "/Users/ting.shao1/Documents/python_ven_hrun/lib/python3.6/site-packages/httprunner/utils.py", line 334, in print_io
    content += prepare_content("Var", _in)
  File "/Users/ting.shao1/Documents/python_ven_hrun/lib/python3.6/site-packages/httprunner/utils.py", line 327, in prepare_content
    content += content_format.format(var_type, variable, value)
TypeError: unsupported format string passed to list.__format__
```

**Comment by fakegeeker** [comment]
@forgetzxy 2.0版本已经取消了这个函数...
