### ISSUE TITLE
测试报告不生成

### ISSUE THREAD

**Issue by linglingfa1212** [HttpRunner/HttpRunner#410]
## 问题描述

遇到大批量测试用例fail的情况下，测试报告不生成

## 版本信息

请提供如下版本信息：

 - 操作系统类型: [centos6.5，win10]
 - Python 版本 [ 3.6]
 - HttpRunner 版本 [1.4.3]

## 堆栈信息

Traceback (most recent call last):
  File "/usr/bin/hrun", line 11, in <module>
    sys.exit(main_hrun())
  File "/usr/lib/python3.6/site-packages/httprunner/cli.py", line 87, in main_hrun
    html_report_template=args.html_report_template
  File "/usr/lib/python3.6/site-packages/httprunner/task.py", line 282, in gen_html_report
    html_report_template
  File "/usr/lib/python3.6/site-packages/httprunner/report.py", line 94, in render_html_report
    stringify_body(meta_data, 'request')
  File "/usr/lib/python3.6/site-packages/httprunner/report.py", line 109, in stringify_body
    headers = meta_data['{}_headers'.format(request_or_response)]
KeyError: 'request_headers'

## 项目文件结构

C:\USERS\USER\DOCUMENTS\INTERFACETEST\TESTS\TESTCASES\YE_CASE\RESOURCE\-A

**Comment by debugtalk** [comment]
@linglingfa1212  1.4.3 版本已经太老了，建议升级到最新版本后再重试下。
