### ISSUE TITLE
运行测试用例提示TypeError: can't pickle LockType objects

### ISSUE THREAD

**Issue by rzhsh1003** [httprunner/httprunner#412]
## 问题描述

运行测试用例提示TypeError: can't pickle LockType objects

## 版本信息

请提供如下版本信息：

 - 操作系统类型: [e.g. , Windows10]
 - Python 版本 [e.g. 3.6]
 - HttpRunner 版本 [e.g. 1.5.14]

## 堆栈信息

Traceback (most recent call last):
  File "E:\Synative_Ren\IVE_Automation\TFwork\test_ive\Run_Tests.py", line 24, in <module>
    runner.run("testcases/v1/")
  File "D:\Program Files (x86)\Python36\lib\site-packages\httprunner\api.py", line 236, in run
    return self._run_tests(testcases, mapping)
  File "D:\Program Files (x86)\Python36\lib\site-packages\httprunner\api.py", line 202, in _run_tests
    test_suite = self._add_tests(parsed_testcases_list)
  File "D:\Program Files (x86)\Python36\lib\site-packages\httprunner\api.py", line 82, in _add_tests
    test_runner = runner.Runner(config, self.http_client_session)
  File "D:\Program Files (x86)\Python36\lib\site-packages\httprunner\runner.py", line 29, in __init__
    self.context = Context(config_variables, config_functions)
  File "D:\Program Files (x86)\Python36\lib\site-packages\httprunner\context.py", line 25, in __init__
    self.init_context_variables(level="testcase")
  File "D:\Program Files (x86)\Python36\lib\site-packages\httprunner\context.py", line 36, in init_context_variables
    self.testcase_runtime_variables_mapping = copy.deepcopy(self.TESTCASE_SHARED_VARIABLES_MAPPING)
  File "D:\Program Files (x86)\Python36\lib\copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "D:\Program Files (x86)\Python36\lib\copy.py", line 306, in _reconstruct
    value = deepcopy(value, memo)
  File "D:\Program Files (x86)\Python36\lib\copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "D:\Program Files (x86)\Python36\lib\copy.py", line 280, in _reconstruct
    state = deepcopy(state, memo)
  File "D:\Program Files (x86)\Python36\lib\copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "D:\Program Files (x86)\Python36\lib\copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "D:\Program Files (x86)\Python36\lib\copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "D:\Program Files (x86)\Python36\lib\copy.py", line 215, in _deepcopy_list
    append(deepcopy(a, memo))
  File "D:\Program Files (x86)\Python36\lib\copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "D:\Program Files (x86)\Python36\lib\copy.py", line 280, in _reconstruct
    state = deepcopy(state, memo)
  File "D:\Program Files (x86)\Python36\lib\copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "D:\Program Files (x86)\Python36\lib\copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "D:\Program Files (x86)\Python36\lib\copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "D:\Program Files (x86)\Python36\lib\copy.py", line 280, in _reconstruct
    state = deepcopy(state, memo)
  File "D:\Program Files (x86)\Python36\lib\copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "D:\Program Files (x86)\Python36\lib\copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "D:\Program Files (x86)\Python36\lib\copy.py", line 169, in deepcopy
    rv = reductor(4)
TypeError: can't pickle LockType objects

**Comment by JacobHZ** [comment]
我也遇到了这个问题
MacOS + Python3.6.0 +  HttpRunner1.5.14
