### ISSUE TITLE
httprunner安装问题

### ISSUE THREAD

**Issue by cairuichun** [HttpRunner/HttpRunner#415]
pip install httprunner完成后进行安装校验时直接报错

直接在命令行中执行hrun命令，提示ImportError: No module named ordered_dict，具体如下：
# httprunner
Traceback (most recent call last):
  File "/usr/local/bin/httprunner", line 7, in <module>
    from httprunner.cli import main_hrun
  File "/usr/local/lib/python2.7/dist-packages/httprunner/__init__.py", line 9, in <module>
    from httprunner.api import HttpRunner, LocustRunner
  File "/usr/local/lib/python2.7/dist-packages/httprunner/api.py", line 6, in <module>
    from httprunner import (exceptions, loader, logger, parser, report, runner,
  File "/usr/local/lib/python2.7/dist-packages/httprunner/exceptions.py", line 3, in <module>
    from httprunner.compat import JSONDecodeError, FileNotFoundError
  File "/usr/local/lib/python2.7/dist-packages/httprunner/compat.py", line 42, in <module>
    from urllib3.packages.ordered_dict import OrderedDict
ImportError: No module named ordered_dict

**Comment by jcuan** [comment]
同样也是安装问题，使用pip装的

**hrun api/crash.yml --log-level debug**
INFO     Loading environment variables from /mnt/d/code/python/worktest/demo/.env
DEBUG    Loaded variable: CRASH_COOKIE
DEBUG    Loaded variable: CRASH_BASE
ERROR    !!!!!!!!!! exception stage: load tests !!!!!!!!!!
Traceback (most recent call last):
  File "/home/jcuan/.local/bin/hrun", line 11, in <module>
    sys.exit(main_hrun())
  File "/home/jcuan/.local/lib/python3.6/site-packages/httprunner/cli.py", line 86, in main_hrun
    dot_env_path=args.dot_env_path
  File "/home/jcuan/.local/lib/python3.6/site-packages/httprunner/api.py", line 232, in run
    testcases = loader.load_tests(path_or_testcases, dot_env_path)
  File "/home/jcuan/.local/lib/python3.6/site-packages/httprunner/loader.py", line 938, in load_tests
    testcases = load_tests(file_path, dot_env_path)
  File "/home/jcuan/.local/lib/python3.6/site-packages/httprunner/loader.py", line 959, in load_tests
    project_mapping = load_project_tests(path, dot_env_path)
  File "/home/jcuan/.local/lib/python3.6/site-packages/httprunner/loader.py", line 880, in load_project_tests
    project_mapping["def-api"] = load_api_folder(os.path.join(project_working_directory, "api"))
  File "/home/jcuan/.local/lib/python3.6/site-packages/httprunner/loader.py", line 734, in load_api_folder
    api_def = api_dict.pop("def")
KeyError: 'def'

 **hrun --version**
1.5.14

**pip3 --version**
pip 9.0.1 from /usr/lib/python3/dist-packages (python 3.6)

**python3 --version**
Python 3.6.5

**Comment by debugtalk** [comment]
@cairuichun 已修复 Python 2.7 下的 ordered_dict 问题。

建议尽快切换到 Python 3，HttpRunner 即将不再支持 Python 2.7 版本。

**Comment by cairuichun** [comment]
谢谢，后面我已经直接用python3环境去搭建了，然后就运行正常了
