### ISSUE TITLE
KeyError: 'start_at'

### ISSUE THREAD

**Issue by jackiezero** [HttpRunner/HttpRunner#433]
## 问题描述

运行pipenv run python main-debug.py hrun 后
显示NFO     Start to render Html report ...
KeyError: 'start_at'
没有提供其他任何信息，完全不知道该怎么排查错误
## 版本信息

 - 操作系统类型: macOS Mojave
 - Python 版本 3.7
 - HttpRunner 版本 1.5.15

**Comment by littlebabyshit** [comment]
加1

**Comment by debugtalk** [comment]
运行的时候，加上 `--failfast --log-level debug`，就可以查看到堆栈信息了。

**Comment by jackiezero** [comment]
谢谢，已经明白了
```
pipenv run python main-debug.py hrun --failfast --log-level debug
DEBUG    No html report template specified, use default.
INFO     Start to render Html report ...
DEBUG    render data: {'success': True, 'stat': {}, 'time': {}, 'platform': {'httprunner_version': '1.5.15', 'python_version': 'CPython 3.7.0', 'platform': 'Darwin-18.2.0-x86_64-i386-64bit'}, 'details': []}
Traceback (most recent call last):
  File "main-debug.py", line 9, in <module>
    main_hrun()
  File "/Users/yanjiankai/code/HttpRunner/httprunner/cli.py", line 95, in main_hrun
    html_report_template=args.html_report_template
  File "/Users/yanjiankai/code/HttpRunner/httprunner/api.py", line 256, in gen_html_report
    html_report_template
  File "/Users/yanjiankai/code/HttpRunner/httprunner/report.py", line 99, in render_html_report
    start_at_timestamp = int(summary["time"]["start_at"])
KeyError: 'start_at'
```
render data里面的time下并没有值，是因为并没有执行case所以 def _aggregate（）方法中tests_results也是没有值的

```
    def _aggregate(self, tests_results):
        """ aggregate results

        Args:
            tests_results (list): list of (testcase, result)

        """
        self.summary = {
            "success": True,
            "stat": {},
            "time": {},
            "platform": report.get_platform(),
            "details": []
        }

        for tests_result in tests_results:
            testcase, result = tests_result
            testcase_summary = report.get_summary(result)

            self.summary["success"] &= testcase_summary["success"]
            testcase_summary["name"] = testcase.config.get("name")
            testcase_summary["base_url"] = testcase.config.get("request", {}).get("base_url", "")

            in_out = utils.get_testcase_io(testcase)
            utils.print_io(in_out)
            testcase_summary["in_out"] = in_out

            report.aggregate_stat(self.summary["stat"], testcase_summary["stat"])
            report.aggregate_stat(self.summary["time"], testcase_summary["time"])

            self.summary["details"].append(testcase_summary)
```

**Comment by LinForest** [comment]
我也遇到了这样的问题，为什么会没有执行case？

**Comment by jackiezero** [comment]
> 我也遇到了这样的问题，为什么会没有执行case？

运行的命令是pipenv run python main-debug.py hrun  并没有指定case  在生产报告的时候就有问题了，你如果加上一个case有结果就好了

@debugtalk  这个问题是否可以优化一下，给个提示而不是报个错？？
