### ISSUE TITLE
返回body为list-dict结构时extract失败

### ISSUE THREAD

**Issue by xglh** [HttpRunner/HttpRunner#434]
## 问题描述

返回body为list-dict结构时extract失败

## 版本信息
 - HttpRunner 版本 [1.5.9]

## 堆栈信息

Traceback (most recent call last):
  File "C:\Python3\lib\site-packages\httprunner\task.py", line 27, in runTest
    self.test_runner.run_test(self.testcase_dict)
  File "C:\Python3\lib\site-packages\httprunner\runner.py", line 187, in run_test
    self.context.validate(validators, resp_obj)
  File "C:\Python3\lib\site-packages\httprunner\context.py", line 255, in validate
    resp_obj
  File "C:\Python3\lib\site-packages\httprunner\context.py", line 186, in eval_check_item
    check_value = resp_obj.extract_field(check_item)
  File "C:\Python3\lib\site-packages\httprunner\response.py", line 191, in extract_field
    raise exceptions.ParamsError(err_msg)
httprunner.exceptions.ParamsError: Invalid extractor! => 0

## 项目文件结构

请提供测试用例的文件组织结构。比较好的方式是在项目根目录中执行`tree -a`命令。

## 项目文件内容（非必须）

请求返回body:  [{"slug":"e177a206"}]
    extract:
    - lastest_slug: content.0.slug

**Comment by LinForest** [comment]
- lastest_slug: content.body.0.slug
