### ISSUE TITLE
报OSError: OSError: Could not find a suitable TLS CA certificate bundle, invalid path: False  错误

### ISSUE THREAD

**Issue by baoshd** [HttpRunner/HttpRunner#438]
python3.6 ，win10
 Https使用"verify": "False",后，报下面的错误，不知道如何解决
OSError: Could not find a suitable TLS CA certificate bundle, invalid path: False

**Comment by debugtalk** [comment]
False 是 bool 型，不能加引号。

```bash
>>>> import requests
>>>> requests.get('https://debugtalk.com')
<Response [200]>
>>>> requests.get('https://debugtalk.com', verify=False)
/Users/debugtalk/.venv/pypy/site-packages/urllib3/connectionpool.py:847: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
<Response [200]>
>>>> requests.get('https://debugtalk.com', verify="False")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/debugtalk/.venv/pypy/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/Users/debugtalk/.venv/pypy/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/debugtalk/.venv/pypy/site-packages/requests/sessions.py", line 524, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/debugtalk/.venv/pypy/site-packages/requests/sessions.py", line 637, in send
    r = adapter.send(request, **kwargs)
  File "/Users/debugtalk/.venv/pypy/site-packages/requests/adapters.py", line 416, in send
    self.cert_verify(conn, request.url, verify, cert)
  File "/Users/debugtalk/.venv/pypy/site-packages/requests/adapters.py", line 228, in cert_verify
    "invalid path: {}".format(cert_loc))
OSError: Could not find a suitable TLS CA certificate bundle, invalid path: False
```
