### ISSUE TITLE
win10 python3.6.5 - pipenv install --dev 报错

### ISSUE THREAD

**Issue by wonderfulwxw** [HttpRunner/HttpRunner#444]
## 问题描述
win10 python3.6.5 - pipenv install --dev 报错

## 版本信息

 - 操作系统类型: [Win10]
 - Python 版本 [3.6.5]
 - HttpRunner 版本 [1.5.15]

## 堆栈信息
```
$ pipenv install --dev
Creating a virtualenv for this project▒▒
Pipfile: D:\git\HttpRunner\Pipfile
Using d:\program files\python3\python3.exe (3.6.5) to create virtualenv▒▒
Exception in thread Thread-3:
Traceback (most recent call last):
  File "d:\program files\python3\lib\threading.py", line 916, in _bootstrap_inne                                                                                                              r
    self.run()
  File "d:\program files\python3\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "d:\program files\python3\lib\site-packages\pipenv\vendor\yaspin\core.py"                                                                                                              , line 330, in _spin
    sys.stdout.write(out)
  File "d:\program files\python3\lib\site-packages\pipenv\vendor\colorama\ansito                                                                                                              win32.py", line 40, in write
    self.__convertor.write(text)
  File "d:\program files\python3\lib\site-packages\pipenv\vendor\colorama\ansito                                                                                                              win32.py", line 141, in write
    self.write_and_convert(text)
  File "d:\program files\python3\lib\site-packages\pipenv\vendor\colorama\ansito                                                                                                              win32.py", line 166, in write_and_convert
    self.write_plain_text(text, cursor, start)
  File "d:\program files\python3\lib\site-packages\pipenv\vendor\colorama\ansito                                                                                                              win32.py", line 174, in write_plain_text
    self.wrapped.write(text[start:end])
  File "d:\program files\python3\lib\site-packages\pipenv\vendor\colorama\ansito                                                                                                              win32.py", line 40, in write
    self.__convertor.write(text)
  File "d:\program files\python3\lib\site-packages\pipenv\vendor\colorama\ansito                                                                                                              win32.py", line 141, in write
    self.write_and_convert(text)
  File "d:\program files\python3\lib\site-packages\pipenv\vendor\colorama\ansito                                                                                                              win32.py", line 169, in write_and_convert
    self.write_plain_text(text, cursor, len(text))
  File "d:\program files\python3\lib\site-packages\pipenv\vendor\colorama\ansito                                                                                                              win32.py", line 174, in write_plain_text
    self.wrapped.write(text[start:end])
  File "d:\program files\python3\lib\site-packages\pipenv\vendor\colorama\ansito                                                                                                              win32.py", line 40, in write
    self.__convertor.write(text)
  File "d:\program files\python3\lib\site-packages\pipenv\vendor\colorama\ansito                                                                                                              win32.py", line 141, in write
    self.write_and_convert(text)
  File "d:\program files\python3\lib\site-packages\pipenv\vendor\colorama\ansito                                                                                                              win32.py", line 169, in write_and_convert
    self.write_plain_text(text, cursor, len(text))
  File "d:\program files\python3\lib\site-packages\pipenv\vendor\colorama\ansito                                                                                                              win32.py", line 174, in write_plain_text
    self.wrapped.write(text[start:end])
UnicodeEncodeError: 'gbk' codec can't encode character '\u280b' in position 1: i                                                                                                              llegal multibyte sequence




Complete
Already using interpreter d:\program files\python3\python3.exe
Using base prefix 'd:\\program files\\python3'
New python executable in C:\Users\admin\.virtualenvs\HttpRunner-vkdoCdGR\Scripts                                                                                                              \python3.exe
Also creating executable in C:\Users\admin\.virtualenvs\HttpRunner-vkdoCdGR\Scri                                                                                                              pts\python.exe
Installing setuptools, pip, wheel...
done.
Virtualenv location: C:\Users\admin\.virtualenvs\HttpRunner-vkdoCdGR
Pipfile.lock not found, creating▒▒
Locking [dev-packages] dependencies▒▒
Traceback (most recent call last):
  File "d:\program files\python3\lib\site-packages\pipenv\vendor\pexpect\expect.                                                                                                              py", line 109, in expect_loop
    return self.timeout()
  File "d:\program files\python3\lib\site-packages\pipenv\vendor\pexpect\expect.                                                                                                              py", line 82, in timeout
    raise TIMEOUT(msg)
pexpect.exceptions.TIMEOUT: <pexpect.popen_spawn.PopenSpawn object at 0x00000273                                                                                                              46AD8358>
searcher: searcher_re:
    0: re.compile('\n')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\program files\python3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "d:\program files\python3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\Program Files\python3\Scripts\pipenv.exe\__main__.py", line 9, in <mo                                                                                                              dule>
  File "d:\program files\python3\lib\site-packages\pipenv\vendor\click\core.py",                                                                                                               line 764, in __call__
    return self.main(*args, **kwargs)
  File "d:\program files\python3\lib\site-packages\pipenv\vendor\click\core.py",                                                                                                               line 717, in main
    rv = self.invoke(ctx)
  File "d:\program files\python3\lib\site-packages\pipenv\vendor\click\core.py",                                                                                                               line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "d:\program files\python3\lib\site-packages\pipenv\vendor\click\core.py",                                                                                                               line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "d:\program files\python3\lib\site-packages\pipenv\vendor\click\core.py",                                                                                                               line 555, in invoke
    return callback(*args, **kwargs)
  File "d:\program files\python3\lib\site-packages\pipenv\vendor\click\decorator                                                                                                              s.py", line 64, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "d:\program files\python3\lib\site-packages\pipenv\vendor\click\core.py",                                                                                                               line 555, in invoke
    return callback(*args, **kwargs)
  File "d:\program files\python3\lib\site-packages\pipenv\vendor\click\decorator                                                                                                              s.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "d:\program files\python3\lib\site-packages\pipenv\cli\command.py", line                                                                                                               249, in install
    editable_packages=state.installstate.editables,
  File "d:\program files\python3\lib\site-packages\pipenv\core.py", line 1872, i                                                                                                              n do_install
    keep_outdated=keep_outdated
  File "d:\program files\python3\lib\site-packages\pipenv\core.py", line 1223, i                                                                                                              n do_init
    pypi_mirror=pypi_mirror,
  File "d:\program files\python3\lib\site-packages\pipenv\core.py", line 1047, i                                                                                                              n do_lock
    lockfile=lockfile
  File "d:\program files\python3\lib\site-packages\pipenv\utils.py", line 620, i                                                                                                              n venv_resolve_deps
    c = resolve(cmd, sp)
  File "d:\program files\python3\lib\site-packages\pipenv\utils.py", line 503, i                                                                                                              n resolve
    result = c.expect(u"\n", timeout=environments.PIPENV_TIMEOUT)
  File "d:\program files\python3\lib\site-packages\pipenv\vendor\delegator.py",                                                                                                               line 215, in expect
    self.subprocess.expect(pattern=pattern, timeout=timeout)
  File "d:\program files\python3\lib\site-packages\pipenv\vendor\pexpect\spawnba                                                                                                              se.py", line 341, in expect
    timeout, searchwindowsize, async_)
  File "d:\program files\python3\lib\site-packages\pipenv\vendor\pexpect\spawnba                                                                                                              se.py", line 369, in expect_list
    return exp.expect_loop(timeout)
  File "d:\program files\python3\lib\site-packages\pipenv\vendor\pexpect\expect.                                                                                                              py", line 119, in expect_loop
    return self.timeout(e)
  File "d:\program files\python3\lib\site-packages\pipenv\vendor\pexpect\expect.                                                                                                              py", line 82, in timeout
    raise TIMEOUT(msg)
pexpect.exceptions.TIMEOUT: <pexpect.popen_spawn.PopenSpawn object at 0x00000273                                                                                                              46AD8358>
searcher: searcher_re:
    0: re.compile('\n')
<pexpect.popen_spawn.PopenSpawn object at 0x0000027346AD8358>
searcher: searcher_re:
    0: re.compile('\n')
```

## 项目文件结构

 tree
.
├── docs
│   ├── CNAME
│   ├── development.md
│   ├── FAQ.md
│   ├── images
│   │   ├── ate-quickstart-demo-report.jpg
│   │   ├── ate-quickstart-http-1.jpg
│   │   ├── ate-quickstart-http-2.jpg
│   │   ├── locusts-full-speed.jpg
│   │   └── qrcode_for_httprunner.jpg
│   ├── index.md
│   ├── Installation.md
│   ├── Introduction.md
│   ├── load-test.md
│   ├── quickstart.md
│   ├── run-testcases.md
│   └── write-testcases.md
├── httprunner
│   ├── __about__.py
│   ├── api.py
│   ├── built_in.py
│   ├── client.py
│   ├── cli.py
│   ├── compat.py
│   ├── context.py
│   ├── exceptions.py
│   ├── __init__.py
│   ├── loader.py
│   ├── locusts.py
│   ├── logger.py
│   ├── parser.py
│   ├── report.py
│   ├── response.py
│   ├── runner.py
│   ├── templates
│   │   ├── locustfile_template
│   │   └── report_template.html
│   ├── utils.py
│   └── validator.py
├── LICENSE
├── main-debug.py
├── mkdocs.yml
├── Pipfile
├── README.md
├── setup.py
└── tests
    ├── api
    │   └── basic.yml
    ├── api_server.py
    ├── base.py
    ├── data
    │   ├── account.csv
    │   ├── app_version.csv
    │   ├── demo_binds.yml
    │   ├── demo_locust.yml
    │   ├── demo_parameters.yml
    │   ├── demo_testcase_cli.yml
    │   ├── demo_testcase_functions.yml
    │   ├── demo_testcase_hardcode.json
    │   ├── demo_testcase_hardcode.yml
    │   ├── demo_testcase_layer.yml
    │   ├── demo_testcase_variables.yml
    │   ├── demo_testcase.yml
    │   ├── test_bugfix.yml
    │   ├── test.env
    │   └── user_agent.csv
    ├── debugtalk.py
    ├── httpbin
    │   ├── basic.yml
    │   ├── hooks.yml
    │   ├── load_image.yml
    │   ├── upload.yml
    │   └── validate.yml
    ├── __init__.py
    ├── suite
    │   ├── create_and_get.yml
    │   └── setup.yml
    ├── test_api.py
    ├── test_apiserver.py
    ├── testcases
    │   └── smoketest.yml
    ├── test_client.py
    ├── test_context.py
    ├── test_loader.py
    ├── test_parser.py
    ├── test_response.py
    ├── test_runner.py
    ├── test_utils.py
    └── test_validator.py

**Comment by wonderfulwxw** [comment]
更换 默认编码为utf-8的终端 安装，问题解决。
