### ISSUE TITLE
深拷贝浅拷贝问题

### ISSUE THREAD

**Issue by SuperLittleH** [HttpRunner/HttpRunner#445]
## 问题描述

您好 我在项目中遇到下面问题 您看看是什么情况：

```
Traceback (most recent call last):
  File "/usr/local/bin/hrun", line 11, in <module>
    load_entry_point('HttpRunner==1.5.15', 'console_scripts', 'hrun')()
  File "/usr/local/lib/python3.5/dist-packages/httprunner/cli.py", line 86, in main_hrun
    dot_env_path=args.dot_env_path
  File "/usr/local/lib/python3.5/dist-packages/httprunner/api.py", line 236, in run
    return self._run_tests(testcases, mapping)
  File "/usr/local/lib/python3.5/dist-packages/httprunner/api.py", line 202, in _run_tests
    test_suite = self._add_tests(parsed_testcases_list)
  File "/usr/local/lib/python3.5/dist-packages/httprunner/api.py", line 82, in _add_tests
    test_runner = runner.Runner(config, self.http_client_session)
  File "/usr/local/lib/python3.5/dist-packages/httprunner/runner.py", line 29, in __init__
    self.context = Context(config_variables, config_functions)
  File "/usr/local/lib/python3.5/dist-packages/httprunner/context.py", line 30, in __init__
    self.init_context_variables(level="testcase")
  File "/usr/local/lib/python3.5/dist-packages/httprunner/context.py", line 41, in init_context_variables
    self.testcase_runtime_variables_mapping = copy.deepcopy(self.TESTCASE_SHARED_VARIABLES_MAPPING)
  File "/usr/lib/python3.5/copy.py", line 182, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "/usr/lib/python3.5/copy.py", line 320, in _reconstruct
    value = deepcopy(value, memo)
  File "/usr/lib/python3.5/copy.py", line 182, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "/usr/lib/python3.5/copy.py", line 297, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/lib/python3.5/copy.py", line 155, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.5/copy.py", line 243, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib/python3.5/copy.py", line 182, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "/usr/lib/python3.5/copy.py", line 297, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/lib/python3.5/copy.py", line 155, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.5/copy.py", line 243, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib/python3.5/copy.py", line 166, in deepcopy
    y = copier(memo)
TypeError: cannot deepcopy this pattern object
```

## 版本信息

 - 操作系统类型: [e.g. Linux,]
 - Python 版本 [e.g. 3.5]
 - HttpRunner 版本 [e.g. 1.5.11]

**Comment by debugtalk** [comment]
@SuperLittleH 该问题在 2.0 中已经不再存在，你可以使用 2.0 版本再试下。

**Comment by SuperLittleH** [comment]
您好 2.0的版本源碼 還是這個嗎

**Comment by debugtalk** [comment]
@SuperLittleH `pip install -U httprunner` 即可。
