### ISSUE TITLE
Yaml文件运行生成报告报错

### ISSUE THREAD

**Issue by guwenwenhappy** [HttpRunner/HttpRunner#460]
hrun testcases/Login.yml --log-level debug
INFO     Loading environment variables from E:\Work\code\Third_Automation_Api\.env
DEBUG    Loaded variable: host
DEBUG    Loaded variable: username
DEBUG    Loaded variable: password
DEBUG    No html report template specified, use default.
INFO     Start to render Html report ...
DEBUG    render data: {'success': True, 'stat': {}, 'time': {}, 'platform': {'httprunner_version': '1.5.15', 'python_version': 'CPython 3.7.0', 'platform': 'Windows-7-6.1.7601-SP1'}, 'details': []}
Traceback (most recent call last):
  File "c:\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python37\Scripts\hrun.exe\__main__.py", line 9, in <module>
  File "c:\python37\lib\site-packages\httprunner\cli.py", line 95, in main_hrun
    html_report_template=args.html_report_template
  File "c:\python37\lib\site-packages\httprunner\api.py", line 256, in gen_html_report
    html_report_template
  File "c:\python37\lib\site-packages\httprunner\report.py", line 99, in render_html_report
    start_at_timestamp = int(summary["time"]["start_at"])
KeyError: 'start_at'

同样目录下，同样的代码，json的用例是运行成功的

**Comment by guwenwenhappy** [comment]
yaml文件缩进的问题

**Comment by guwenwenhappy** [comment]
yaml文件的缩进问题导致的
