### ISSUE TITLE
加载了.env文件后，KeyError: 'start_at'

### ISSUE THREAD

**Issue by fuersher** [HttpRunner/HttpRunner#462]
## 问题描述
1. env文件内容：
![image](https://user-images.githubusercontent.com/42135502/49845614-5983ce00-fe02-11e8-96e0-d8c1687ac713.png)
2. debugtalk.py内容
![image](https://user-images.githubusercontent.com/42135502/49845627-67395380-fe02-11e8-9c4b-374bd3f616d3.png)
3.测试用例文件内容
![image](https://user-images.githubusercontent.com/42135502/49845648-820bc800-fe02-11e8-9aad-f00778da7580.png)

## 堆栈信息

```bash
$hrun  /Users/tangxiao/Downloads/httprunnerTest/tests/testcases/Robot_cases/Robot_main.yml
INFO     Loading environment variables from /Users/tangxiao/Downloads/httprunnerTest/tests/.env
DEBUG    No html report template specified, use default.
INFO     Start to render Html report ...
DEBUG    render data: {'success': True, 'stat': {}, 'time': {}, 'platform': {'httprunner_version': '1.5.15', 'python_version': 'CPython 3.7.1', 'platform': 'Darwin-17.7.0-x86_64-i386-64bit'}, 'details': []}
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/bin/hrun", line 11, in <module>
    sys.exit(main_hrun())
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/httprunner/cli.py", line 95, in main_hrun
    html_report_template=args.html_report_template
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/httprunner/api.py", line 256, in gen_html_report
    html_report_template
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/httprunner/report.py", line 99, in render_html_report
    start_at_timestamp = int(summary["time"]["start_at"])
KeyError: 'start_at'
jack-MacBook-Pro:httprunnerTest tangxiao$ hrun /Users/tangxiao/Downloads/httprunnerTest/tests/testcases/Robot_cases/Robot_main.yml
INFO     Loading environment variables from /Users/tangxiao/Downloads/httprunnerTest/tests/.env
INFO     Start to render Html report ...
KeyError: 'start_at'
```

## 版本信息

 - 操作系统类型: [macos]
 - Python 版本 [3.7]
 - HttpRunner 版本 [1.5.15]

**Comment by guwenwenhappy** [comment]
yaml文件的格式有问题，导致用例没有执行

**Comment by fuersher** [comment]
> yaml文件的格式有问题，导致用例没有执行

不加载.env 文件时，yaml文件用例是可以执行的，所以应该不是yaml文件的问题😢

**Comment by zlychelsea** [comment]
碰到了同样的问题，httprunner会退到1.4.8一切正常，一升级就不能用

**Comment by debugtalk** [comment]
HttpRunner 升级后，summary 的数据结构变动后测试报告模板未更新造成的。
升级到最新版本后不再存在。
