### ISSUE TITLE
输出测试报告报错，返回数据中包含中文

### ISSUE THREAD

**Issue by x1070757525** [HttpRunner/HttpRunner#468]
## Describe the bug
这个只是我遇到的问题，我的脚本利用分层机制，在输出测试报告过程中出现报错，无法生产报告，错误阶段：

## Versions

Please complete the following information:

 - Windows
 - Python [ 3.7]
 - HttpRunner [.1.5.11]

## Traceback

Traceback when bug occurs.

## Project structure

一个简单的新建操作。返回数据中包含中文

## Project files (If possible)

Administrator@DESKTOP-JL99425 MINGW64 /e/git_warehouse/AnHui-XiaoXi2.0 (master)
$ hrun testcases/ --log-level debug
INFO     Loading environment variables from E:\git_warehouse\AnHui-XiaoXi2.0\.env
INFO     Start to run testcase: Test_Creat_PageStrategy
Test_Creat_PageStrategy_001
DEBUG    call hook: ${setup_hook_prepare_kwargs($request)}
INFO     POST /message_service/page_strategy
DEBUG    request kwargs(raw): {'headers': {'tokenId': '88d3b2a8-1b31-4249-a89f-5d86fb9fe450', 'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.67 Safari/537.36', 'Content-Type': 'application/json;charset=UTF-8'}, 'json': {'name': '▒▒▒▒▒▒', 'code': 'iqyi'}}
DEBUG    processed request:
> POST http://192.168.2.204:8069/message_service/page_strategy
> kwargs: {'headers': {'tokenId': '88d3b2a8-1b31-4249-a89f-5d86fb9fe450', 'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.67 Safari/537.36', 'Content-Type': 'application/json;charset=UTF-8'}, 'json': {'name': '▒▒▒▒▒▒', 'code': 'iqyi'}, 'timeout': 120}
DEBUG
================== request details ==================
url              : 'http://192.168.2.204:8069/message_service/page_strategy'
method           : 'POST'
headers          : {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.67 Safari/537.36', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'tokenId': '88d3b2a8-1b31-4249-a89f-5d86fb9fe450', 'Content-Type': 'application/json;charset=UTF-8', 'Content-Length': '46'}
start_timestamp  : 1544779965.9531786
json             : {'name': '▒▒▒▒▒▒', 'code': 'iqyi'}
body             : b'{"name": "\\u7231\\u5947\\u827a", "code": "iqyi"}'

DEBUG
================== response details ==================
status_code      : 200
headers          : {'Server': 'nginx/1.12.1', 'Date': 'Fri, 14 Dec 2018 09:31:09 GMT', 'Content-Type': 'application/json;charset=UTF-8', 'Content-Length': '128', 'Connection': 'keep-alive'}
content_size     : 128
response_time_ms : 249.03
elapsed_ms       : 242.355
encoding         : 'UTF-8'
content          : b'{"code":200,"msg":"SUCCESS","data":{"id":null,"code":"iqyi","name":"\xe7\x88\xb1\xe5\xa5\x87\xe8\x89\xba","pageId":"1d65f22b-f191-43e1-a8f0-f6aa7a41800d"}}'
content_type     : 'application/json;charset=UTF-8'
ok               : True
url              : 'http://192.168.2.204:8069/message_service/page_strategy'
reason           : ''
cookies          : {}
text             : '{"code":200,"msg":"SUCCESS","data":{"id":null,"code":"iqyi","name":"▒▒▒▒▒▒","pageId":"1d65f22b-f191-43e1-a8f0-f6aa7a41800d"}}'
json             : {'code': 200, 'msg': 'SUCCESS', 'data': {'id': None, 'code': 'iqyi', 'name': '▒▒▒▒▒▒', 'pageId': '1d65f22b-f191-43e1-a8f0-f6aa7a41800d'}}

INFO     status_code: 200, response_time(ms): 249.03 ms, response_length: 128 bytes
INFO     start to validate.
DEBUG    extract: status_code   => 200
DEBUG    validate: status_code equals 200(int)  ==> pass
DEBUG    extract: content.code  => 200
DEBUG    validate: content.code equals 200(int) ==> pass
DEBUG    extract: content.msg   => SUCCESS
DEBUG    validate: content.msg equals SUCCESS(str)      ==> pass
DEBUG    extract: content.data.name     => ▒▒▒▒▒▒
DEBUG    validate: content.data.name equals ▒▒▒▒▒▒(str) ==> pass
DEBUG    extract: content.data.code     => iqyi
DEBUG    validate: content.data.code equals iqyi(str)   ==> pass
.

----------------------------------------------------------------------
Ran 1 test in 0.257s

OK
ERROR    !!!!!!!!!! exception stage: aggregate results !!!!!!!!!!
Traceback (most recent call last):
  File "d:\program files (x86)\python37-32\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "d:\program files (x86)\python37-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\Program Files (x86)\Python37-32\Scripts\hrun.exe\__main__.py", line 9, in <module>
  File "d:\program files (x86)\python37-32\lib\site-packages\httprunner\cli.py", line 86, in main_hrun
    dot_env_path=args.dot_env_path
  File "d:\program files (x86)\python37-32\lib\site-packages\httprunner\api.py", line 236, in run
    return self._run_tests(testcases, mapping)
  File "d:\program files (x86)\python37-32\lib\site-packages\httprunner\api.py", line 208, in _run_tests
    self._aggregate(results)
  File "d:\program files (x86)\python37-32\lib\site-packages\httprunner\api.py", line 147, in _aggregate
    utils.print_io(in_out)
  File "d:\program files (x86)\python37-32\lib\site-packages\httprunner\utils.py", line 388, in print_io
    content += prepare_content("Var", _in)
  File "d:\program files (x86)\python37-32\lib\site-packages\httprunner\utils.py", line 381, in prepare_content
    content += content_format.format(var_type, variable, value)
TypeError: unsupported format string passed to Common.__format__

**Comment by x1070757525** [comment]
是因为我在使用configparser的时候，引入配置变量导致错误
