### ISSUE TITLE
输出测试报告报错

### ISSUE THREAD

**Issue by x1070757525** [HttpRunner/HttpRunner#469]
## Describe the bug

TypeError: unsupported format string passed to Common.__format__

执行方式：httprunner testcases --log-level debug
## Versions

Please complete the following information:

 -  Windows
 - Python 3.7
 - HttpRunner 1.5.15

## Traceback

原始的报错：
`Ran 1 test in 0.073s

FAILED (failures=1)
ERROR    !!!!!!!!!! exception stage: aggregate results !!!!!!!!!!
Traceback (most recent call last):
  File "D:\Program Files (x86)\Python37-32\Scripts\httprunner-script.py", line 11, in <module>
    load_entry_point('HttpRunner==1.5.15', 'console_scripts', 'httprunner')()
  File "d:\program files (x86)\python37-32\lib\site-packages\httprunner\cli.py", line 86, in main_hrun
    dot_env_path=args.dot_env_path
  File "d:\program files (x86)\python37-32\lib\site-packages\httprunner\api.py", line 236, in run
    return self._run_tests(testcases, mapping)
  File "d:\program files (x86)\python37-32\lib\site-packages\httprunner\api.py", line 208, in _run_tests
    self._aggregate(results)
  File "d:\program files (x86)\python37-32\lib\site-packages\httprunner\api.py", line 147, in _aggregate
    utils.print_io(in_out)
  File "d:\program files (x86)\python37-32\lib\site-packages\httprunner\utils.py", line 388, in print_io
    content += prepare_content("Var", _in)
  File "d:\program files (x86)\python37-32\lib\site-packages\httprunner\utils.py", line 381, in prepare_content
    content += content_format.format(var_type,variable,value)
TypeError: unsupported format string passed to Common.__format__`

当我在该位置添加print，输出了var_type,variable,value三个变量后：

`Ran 1 test in 0.079s

FAILED (failures=1)
var_type = Var
variable = New_PageName
value = TEST213
var_type = Var
variable = New_PageCode
value = aiqiyi
var_type = Var
variable = common
ERROR    !!!!!!!!!! exception stage: aggregate results !!!!!!!!!!
Traceback (most recent call last):
  File "D:\Program Files (x86)\Python37-32\Scripts\httprunner-script.py", line 11, in <module>
    load_entry_point('HttpRunner==1.5.15', 'console_scripts', 'httprunner')()
  File "d:\program files (x86)\python37-32\lib\site-packages\httprunner\cli.py", line 86, in main_hrun
    dot_env_path=args.dot_env_path
  File "d:\program files (x86)\python37-32\lib\site-packages\httprunner\api.py", line 236, in run
    return self._run_tests(testcases, mapping)
  File "d:\program files (x86)\python37-32\lib\site-packages\httprunner\api.py", line 208, in _run_tests
    self._aggregate(results)
  File "d:\program files (x86)\python37-32\lib\site-packages\httprunner\api.py", line 147, in _aggregate
    utils.print_io(in_out)
  File "d:\program files (x86)\python37-32\lib\site-packages\httprunner\utils.py", line 391, in print_io
    content += prepare_content("Var", _in)
  File "d:\program files (x86)\python37-32\lib\site-packages\httprunner\utils.py", line 382, in prepare_content
    print("value = "+ value)
TypeError: can only concatenate str (not "Common") to str`

**Comment by x1070757525** [comment]
原因：我的debugtalk中添加了一个变量，用来对引入类Common进行命名，但是这里由于未知原因导致报错。去掉变量直接使用Common后，问题解决。
