### ISSUE TITLE
httprunner.exceptions.ParamsError: base url missed!

### ISSUE THREAD

**Issue by Donghaopeng** [HttpRunner/HttpRunner#476]
## 问题描述

用demo-quickstart-5.yml运行case报错：httprunner.exceptions.ParamsError: base url missed!

## 版本信息

 - 操作系统类型: [macos]
 - Python 版本 [3.6]
 - HttpRunner 版本 [2.0.0]

## 项目文件内容（非必须）
```yml
- config:
    name: testcase description
    variables:
        - device_sn: ${gen_random_string(15)}
        - user_id: 1000
    request:
        base_url: http://127.0.0.1:5000
        headers:
            User-Agent: python-requests/2.18.4
            device_sn: $device_sn
            Content-Type: application/json

- test:
    name: /api/get-token
    variables:
        - user_agent: "iOS/10.3"
        - os_platform: "ios"
        - app_version: "2.8.6"
    request:
        url: /api/get-token
        method: POST
        headers:
            app_version: $app_version
            os_platform: $os_platform
            user_agent: $user_agent
        json:
            sign: ${get_sign($user_agent, $device_sn, $os_platform, $app_version)}
    extract:
        - token: content.token
    validate:
        - eq: [status_code, 200]
        - eq: [headers.Content-Type, application/json]
        - eq: [content.success, true]

- test:
    name: /api/users/$user_id
    request:
        url: /api/users/$user_id
        method: POST
        headers:
            token: $token
        json:
            name: user1
            password: '123456'
    validate:
        - eq: [status_code, 201]
        - eq: [headers.Content-Type, application/json]
        - eq: [content.success, true]
        - eq: [content.msg, "user created successfully."]
```
## 报错详细信息
```shell
ERROR: test_0000_000 (httprunner.api.TestSequense)
/api/get-token
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/donghp/.virtualenvs/HttpRunner/lib/python3.7/site-packages/httprunner/api.py", line 54, in test
    test_runner.run_test(test_dict)
  File "/Users/donghp/.virtualenvs/HttpRunner/lib/python3.7/site-packages/httprunner/runner.py", line 347, in run_test
    self._run_test(test_dict)
  File "/Users/donghp/.virtualenvs/HttpRunner/lib/python3.7/site-packages/httprunner/runner.py", line 234, in _run_test
    **parsed_test_request
  File "/Users/donghp/.virtualenvs/HttpRunner/lib/python3.7/site-packages/httprunner/client.py", line 181, in request
    url = build_url(self.base_url, url)
  File "/Users/donghp/.virtualenvs/HttpRunner/lib/python3.7/site-packages/httprunner/utils.py", line 62, in build_url
    raise ParamsError("base url missed!")
httprunner.exceptions.ParamsError: base url missed!
```

## 备注
base_url 加上英文的双引号或单引号''还是一样的报错

**Comment by guolong123** [comment]
貌似base_url需要放置在request外面，与request平级

**Comment by Donghaopeng** [comment]
好的，谢谢，看来是文档的问题。
建议开发团队更新一下文档。
另外，我用
```yml
- eq: [content.success, true]
- eq: [content.msg, "user created successfully."]
````
和
```yml
- eq: [json.success, true]
- eq: [json.msg, "user created successfully."]
```
有什么不一样，好像都能解析出来字段的值

**Comment by debugtalk** [comment]
QuickStart 文档已更新：https://cn.httprunner.org/quickstart/

**Comment by debugtalk** [comment]
@Donghaopeng 是做了处理，在响应结果为 dict 数据类型时，使用 content 和 json 是等价的。
