### ISSUE TITLE
httprunner.exceptions.VariableNotFound

### ISSUE THREAD

**Issue by StandOutstar** [HttpRunner/HttpRunner#478]
## 版本信息
 - 操作系统类型: macos,
 - Python: 3.6
 - HttpRunner 2.0.0

## 堆栈信息
```
Traceback (most recent call last):
  File "/Users/mac/.local/share/virtualenvs/apiautotest-1aGhHem8/lib/python3.6/site-packages/httprunner/parser.py", line 370, in get_mapping_variable
    return variables_mapping[variable_name]
KeyError: 'UserLoginUrl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/mac/.local/share/virtualenvs/apiautotest-1aGhHem8/lib/python3.6/site-packages/httprunner/api.py", line 54, in test
    test_runner.run_test(test_dict)
  File "/Users/mac/.local/share/virtualenvs/apiautotest-1aGhHem8/lib/python3.6/site-packages/httprunner/runner.py", line 347, in run_test
    self._run_test(test_dict)
  File "/Users/mac/.local/share/virtualenvs/apiautotest-1aGhHem8/lib/python3.6/site-packages/httprunner/runner.py", line 202, in _run_test
    parsed_test_request = self.session_context.eval_content(raw_request)
  File "/Users/mac/.local/share/virtualenvs/apiautotest-1aGhHem8/lib/python3.6/site-packages/httprunner/context.py", line 69, in eval_content
    self.FUNCTIONS_MAPPING
  File "/Users/mac/.local/share/virtualenvs/apiautotest-1aGhHem8/lib/python3.6/site-packages/httprunner/parser.py", line 583, in parse_data
    raise_if_variable_not_found
  File "/Users/mac/.local/share/virtualenvs/apiautotest-1aGhHem8/lib/python3.6/site-packages/httprunner/parser.py", line 607, in parse_data
    functions_mapping
  File "/Users/mac/.local/share/virtualenvs/apiautotest-1aGhHem8/lib/python3.6/site-packages/httprunner/parser.py", line 486, in parse_string_variables
    variable_value = get_mapping_variable(variable_name, variables_mapping)
  File "/Users/mac/.local/share/virtualenvs/apiautotest-1aGhHem8/lib/python3.6/site-packages/httprunner/parser.py", line 372, in get_mapping_variable
    raise exceptions.VariableNotFound("{} is not found.".format(variable_name))
httprunner.exceptions.VariableNotFound: UserLoginUrl is not found.
```
## 项目文件内容（非必须）
```yaml
- config:
    name: 登录
    parameters:
      - username-password-device: ${P(data/sign_in.csv)}
    request:
      base_url: $TestHost
      headers:
        Content-Type: application/json
- test:
    name: 登录
    variables:
      - timestamp: ${get_timestamp()}
    request:
      url: $UserLoginUrl
      method: POST
      headers:
        clientId: $ClientID
        timestamp: $timestamp
        sign:  ${get_sign(url=$UserLoginUrl, username=$username, password=$password, device=$device, timestamp=$timestamp)}
      json:
        username: $username
        password: $password
        device: $device
    validate:
      - eq: [status_code, 200]
      - eq: [content.resultCode, "90000"]
      - eq: [content.resultDesc, "success"]
```
V1.5.15 是可以跑通的，升级到 v2.0后出现问题，发现在 variables 中去查找debugtalk传递的环境变量导致出现KeyError。

**Comment by StandOutstar** [comment]
看源码2.0获取环境变量的方式改为了通过environ或ENV函数来获取

**Comment by StandOutstar** [comment]
希望作者尽快提供文档 @debugtalk

**Comment by debugtalk** [comment]
@guolong123 @StandOutstar 通过 ENV 内置方法获取在 .env 中定义的环境变量。
