### ISSUE TITLE
testcase/config/variables之间的引用，返回值不一致

### ISSUE THREAD

**Issue by olihuang** [HttpRunner/HttpRunner#490]
## 问题描述

请对遇到的 bug 进行简要描述。

## 版本信息

请提供如下版本信息：

 - 操作系统类型: [Windows]
 - Python 版本 [3.6.8]
 - HttpRunner 版本 [2.0.0]

## 堆栈信息

```
Traceback (most recent call last):
  File "d:\program files\anaconda3\lib\site-packages\httprunner\api.py", line 54, in test
    test_runner.run_test(test_dict)
httprunner.exceptions.ExtractFailure: Failed to extract! => data.token
response body: {'code': 10005, 'message': 'sig error!'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\program files\anaconda3\lib\site-packages\httprunner\api.py", line 56, in test
    self.fail(str(ex))
AssertionError: Failed to extract! => data.token
response body: {'code': 10005, 'message': 'sig error!'}
```

## 项目文件结构

```
demo
├── api
│   └── open_api
|        └──login.yml
├── reports
├── debugtalk.py
├── testcases
│  └──open_api
│       └──base
|            └──interface_authentication.yml
|——.env                        
└── testsuites
```

请提供测试用例的文件组织结构。比较好的方式是在项目根目录中执行`tree -a`命令。

## 项目文件内容（非必须）
![image](https://user-images.githubusercontent.com/35990310/50969125-515da200-1518-11e9-99aa-d0e80d88cf4a.png)

提示：请注意在去除项目敏感信息（IP、账号密码、密钥等）后再进行上传。

**Comment by debugtalk** [comment]
@olihuang 看你的截图没有看出问题。看你的堆栈信息，就是返回信息里面没有 token 字段。

```
httprunner.exceptions.ExtractFailure: Failed to extract! => data.token
response body: {'code': 10005, 'message': 'sig error!'}
```
