### ISSUE TITLE
测试时出现，TypeError: cannot concatenate 'str' and 'NoneType' objects

### ISSUE THREAD

**Issue by huaweihulk** [HttpRunner/HttpRunner#509]
ERROR    !!!!!!!!!! exception stage: run test suite !!!!!!!!!!
Traceback (most recent call last):
  File "/usr/local/bin/hrun", line 10, in <module>
    sys.exit(main_hrun())
  File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/httprunner/cli.py", line 82, in main_hrun
    runner.run(path, dot_env_path=args.dot_env_path)
  File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/httprunner/api.py", line 229, in run
    return self.run_path(path_or_tests, dot_env_path, mapping)
  File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/httprunner/api.py", line 217, in run_path
    return self.run_tests(tests_mapping)
  File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/httprunner/api.py", line 173, in run_tests
    results = self._run_suite(test_suite)
  File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/httprunner/api.py", line 110, in _run_suite
    result = self.unittest_runner.run(testcase)
  File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/runner.py", line 176, in run
    test(result)
  File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/suite.py", line 122, in run
    test(result)
  File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/case.py", line 663, in __call__
    return self.run(*args, **kwds)
  File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/case.py", line 588, in run
    result.startTest(self)
  File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/httprunner/report.py", line 341, in startTest
    logger.color_print(test.shortDescription(), "yellow")
  File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/httprunner/logger.py", line 56, in color_print
    print(fore_color + msg)
TypeError: can only concatenate str (not "NoneType") to str

系统环境是mac,python版本是3.7

**Comment by Jaydanna** [comment]
请问现在解决了吗，我也遇到这个问题

**Comment by huaweihulk** [comment]
> 请问现在解决了吗，我也遇到这个问题

我一开始时怀疑python版本问题，但是实际上是脚本的某个地方写错了，所以还是关注下脚本的问题。但是这个error的提示真的有点让人摸不着头脑

**Comment by hstart** [comment]
1、问题原因：print(fore_color + msg) 这里面msg是None 这样 字符串+None python 会出错。
2、解决方案：
修改 site-packages/httprunner/logger.py 中的 color_print 函数。
将 **print(fore_color + msg)**
修改为：**print("{}{}".format(fore_color,msg))**

**Comment by hstart** [comment]
1、出现这种原因一般是 method 方法是一个不正确的。例如CENNECT  。 这种一般容易出现在抓包的时候没有对抓包后的脚本做处理。
2、例如以下是一个会出错的例子。可以复现上述问题。
{
    "config": {
        "name": "testcase description",
        "variables": {}
    },
    "teststeps": [
        {
            "name": "",
            "request": {
                "url": "https://e.crashlytics.com",
                "method": "CONNECT",
                "headers": {
                    "User-Agent": "Answers iOS SDK/1.4.0",
                    "Proxy-Connection": "keep-alive"
                }
            },
            "validate": [
                {
                    "eq": [
                        "status_code",
                        200
                    ]
                }
            ]
        }
    ]
}
