### ISSUE TITLE
期望 times 支持参数化

### ISSUE THREAD

**Issue by Xweirdo** [HttpRunner/HttpRunner#551]
## 问题描述
现在以times: $times 运行时会直接将“$times”传到后台

## 版本信息
V2.0.5
请提供如下版本信息：

 - 操作系统类型:  Linux
 - Python 版本  3.6.5
 - HttpRunner 版本 2.0.5

## 堆栈信息

Traceback (most recent call last):
  File "/home/test/virtualenv/bin/hrun", line 11, in <module>
    sys.exit(main_hrun())
  File "/home/test/virtualenv/lib/python3.6/site-packages/httprunner/cli.py", line 82, in main_hrun
    runner.run(path, dot_env_path=args.dot_env_path)
  File "/home/test/virtualenv/lib/python3.6/site-packages/httprunner/api.py", line 258, in run
    return self.run_path(path_or_tests, dot_env_path, mapping)
  File "/home/test/virtualenv/lib/python3.6/site-packages/httprunner/api.py", line 246, in run_path
    return self.run_tests(tests_mapping)
  File "/home/test/virtualenv/lib/python3.6/site-packages/httprunner/api.py", line 172, in run_tests
    test_suite = self._add_tests(parsed_tests_mapping)
  File "/home/test/virtualenv/lib/python3.6/site-packages/httprunner/api.py", line 79, in _add_tests
    for times_index in range(int(test_dict.get("times", 1))):
ValueError: invalid literal for int() with base 10: '${get_times($times)}'

**Comment by debugtalk** [comment]
@Xweirdo times 机制出现在初始化测试用例阶段，此时还没有涉及到变量解析。

如果要实现这个机制，有三种情况：

1、times 出现在当前 step 的 variables 中并且是确定的值，可实现，但没实际意义；
2、times 出现在当前 step 的variables 中，需要通过函数运行得到，可实现；但如果在调用函数时引用了前置 step 或者 config 中的变量，则无法实现；
3、times 由前置 step extract 得到，无法实现。

综合这几种情况，不会考虑对 times 实现参数化，但可以在该处代码处做数值校验，进行明确提示。
