### ISSUE TITLE
访问接口时提示“SSLError: bad handshake”

### ISSUE THREAD

**Issue by yanghuo662** [HttpRunner/HttpRunner#57]
接口地址：https://11.12.112.212:6666/open/api/v1/ticket/getChallengeByAccount
执行用例时提示：SSLError("bad handshake: Error([('SSL routines', 'tls_process_s
erver_certificate', 'certificate verify failed')
目前采用这个方法解决：pip uninstall -y certifi && pip install certifi==2015.04.28 
不知道这样有没有问题

**Comment by yanghuo662** [comment]
貌似这样不行，再次执行后提示：
Traceback (most recent call last):
  File "d:\python\lib\site-packages\pkg_resources\__init__.py", line 651, in _bu
ild_master
    ws.require(__requires__)
  File "d:\python\lib\site-packages\pkg_resources\__init__.py", line 952, in req
uire
    needed = self.resolve(parse_requirements(requirements))
  File "d:\python\lib\site-packages\pkg_resources\__init__.py", line 844, in res
olve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (certifi 2015.4.28 (d:\python\lib\site-
packages), Requirement.parse('certifi>=2017.4.17'), {'requests'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\python\Scripts\httprunner-script.py", line 5, in <module>
    from pkg_resources import load_entry_point
  File "d:\python\lib\site-packages\pkg_resources\__init__.py", line 3084, in <m
odule>
    @_call_aside
  File "d:\python\lib\site-packages\pkg_resources\__init__.py", line 3070, in _c
all_aside
    f(*args, **kwargs)
  File "d:\python\lib\site-packages\pkg_resources\__init__.py", line 3097, in _i
nitialize_master_working_set
    working_set = WorkingSet._build_master()
  File "d:\python\lib\site-packages\pkg_resources\__init__.py", line 653, in _bu
ild_master
    return cls._build_from_requirements(__requires__)
  File "d:\python\lib\site-packages\pkg_resources\__init__.py", line 666, in _bu
ild_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "d:\python\lib\site-packages\pkg_resources\__init__.py", line 839, in res
olve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'certifi>=2017.4.17' distribution was no
t found and is required by requests

**Comment by debugtalk** [comment]
@yanghuo662 可能是你被测系统的HTTPS证书配置有问题。要么修复证书配置，要么在发起请求的时候，将verify设置为False。

```yaml
- config:
    request:
        verify: false
```
