### ISSUE TITLE
ModuleNotFoundError: No module named 'pyunitreport'

### ISSUE THREAD

**Issue by rainy0824** [HttpRunner/HttpRunner#58]
```
    from httprunner.cli import main_ate
  File "/usr/local/lib/python3.6/site-packages/httprunner/cli.py", line 7, in <module>
    from pyunitreport import __version__ as pyu_version
ModuleNotFoundError: No module named 'pyunitreport'
```

**Comment by debugtalk** [comment]
@rainy0824 

升级一下`PyUnitReport`再看下。

```bash
$ pip install -U pyunitreport
```

**Comment by rainy0824** [comment]
@debugtalk  还是一样的。pyunitreport 版本：PyUnitReport (0.1.3b0)

**Comment by rainy0824** [comment]
@debugtalk  我把cli.py 里面pyunitreport改成大写就可以了，httprunner:0.8.1.a ,pyunitreport:0.1.3b 不用改动，更新到0.8.1.1，就的改，楼主看下

**Comment by debugtalk** [comment]
感谢反馈。我更新了下版本号，你再看下？

```bash
$ pip install -U httprunner --no-cache-dir
$ hrun -V
HttpRunner version: 0.8.2
PyUnitReport version: 0.1.3b
```

**Comment by rainy0824** [comment]
@debugtalk  更新后，httprunner:0.8.2 ,pyunitreport:0.1.3.b 还是提示找不到，报错：
Traceback (most recent call last):
  File "/usr/local/bin/hrun", line 11, in <module>
    load_entry_point('HttpRunner==0.8.2', 'console_scripts', 'hrun')()
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 561, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2631, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2291, in load
    return self.resolve()
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2297, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.6/site-packages/httprunner/cli.py", line 7, in <module>
    from pyunitreport import __version__ as pyu_version
ModuleNotFoundError: No module named 'pyunitreport'

**Comment by debugtalk** [comment]
@rainy0824 找到问题的原因了，是之前更改包名大小写的时候没有改成功。已经修复了，你可以再试下么？

**Comment by Bakho** [comment]
Open command line and run 
pip install pyunitreport

**Comment by rainy0824** [comment]
@debugtalk   可以了
