### ISSUE TITLE
引用测试用例json格式无效

### ISSUE THREAD

**Issue by yxp1061** [HttpRunner/HttpRunner#610]
## 问题描述

请对遇到的 bug 进行简要描述。

## 版本信息

请提供如下版本信息：

 - 操作系统类型: [Windows]
 - Python 版本 [e.g. 3.6]
 - HttpRunner 版本 [e.g. 2.1.2]

```bash
D:\pychar\hrun_demo>hrun testcases\ab.json
INFO     Loading environment variables from D:\pychar\hrun_demo\.env
ERROR    !!!!!!!!!! exception stage: load tests !!!!!!!!!!
AttributeError: 'list' object has no attribute 'get'
 ```

具体详细日志：

```
Traceback (most recent call last):
  File "d:\pychar\py3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "d:\pychar\py3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\pychar\py3\Scripts\hrun.exe\__main__.py", line 9, in <module>
  File "d:\pychar\py3\lib\site-packages\httprunner\cli.py", line 83, in main_hrun
    runner.run(path, dot_env_path=args.dot_env_path)
  File "d:\pychar\py3\lib\site-packages\httprunner\api.py", line 264, in run
    return self.run_path(path_or_tests, dot_env_path, mapping)
  File "d:\pychar\py3\lib\site-packages\httprunner\api.py", line 246, in run_path
    tests_mapping = loader.load_tests(path, dot_env_path)
  File "d:\pychar\py3\lib\site-packages\httprunner\loader.py", line 773, in load_tests
    load_project_tests(path, dot_env_path)
  File "d:\pychar\py3\lib\site-packages\httprunner\loader.py", line 708, in load_project_tests
    tests_def_mapping["api"] = load_api_folder(os.path.join(project_working_directory, "api"))
  File "d:\pychar\py3\lib\site-packages\httprunner\loader.py", line 623, in load_api_folder
    api_id = api_dict.get("id") or api_dict.get("def") or api_dict.get("name")
AttributeError: 'list' object has no attribute 'get'
```

如果是hrun testcases\ab.yml能运行成功。

**Comment by debugtalk** [comment]
@yxp1061 提供下 JSON 用例内容。
