### ISSUE TITLE
在testcase中引用api，提示AssertionError: validator should be parsed first

### ISSUE THREAD

**Issue by EricYou1987** [HttpRunner/httprunner#653]
## 问题描述
在testcase中引用api，提示AssertionError: validator should be parsed first

## 版本信息

请提供如下版本信息：

 - 操作系统类型: linux
 - Python 版本 3.7.1 
 - HttpRunner 版本 2.2.3

## 项目文件内容（非必须）

testcase文件内容
config:
    name: "demo testcase"
    variables: {}
    base_url: "http://tapi.xxx.com"

teststeps:
-   name: demo step 1
    api: api/api_user_login.yml
    variables:
        password: 123456a
        userId: jhfkkkx1
    validate:
        -   eq:
            - status_code
            - 200
    setup_hooks:
        - ${get_sign($request)}

api_user_login.yml文件内容
config:
    name: api_user_login
    variables:
        password: 123456ab
        userId: jhfkkkx1
teststeps:
-   name: /api/user/account/login
    request:
        data:
            password: $password
            userId: $userId
        headers:
            Content-Type: application/x-www-form-urlencoded
            User-Agent: Mozilla/5.0 (Linux; U; Android 8.1.0; zh-cn; MI 8 SE Build/OPM1.171019.019)
                AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 Mobile Safari/534.30
            api-version: '4'
            passid: appdev
            timestamp: ${get_timestamp()}
        method: POST
        url: http://tapi.xxx.com/api/user/account/login
    validate:
    -   eq:
        - status_code
        - 200

## 运行命令 && 堆栈信息

请提供在命令行中运行测试时所在的目录和命令，以及报错时的详细堆栈内容。

root@test-team-server:/home/eric/HttpRunner/HttpRunner# pipenv run python main-debug.py hrun ./projects/proj_app/testcases/case_user_login_using_mobile.yml --log-file ./projects/proj_app/logs/2.log --log-level DEBUG
Loading .env environment variables…
api_user_login
F

======================================================================
FAIL: test_0000_000 (httprunner.api.TestSequense)
api_user_login
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/eric/HttpRunner/HttpRunner/httprunner/api.py", line 54, in test
    test_runner.run_test(test_dict)
httprunner.exceptions.ValidationFailure: validator should be parsed first: [{'eq': ['status_code', 200]}]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/eric/HttpRunner/HttpRunner/httprunner/api.py", line 56, in test
    self.fail(str(ex))
AssertionError: validator should be parsed first: [{'eq': ['status_code', 200]}]

**Comment by EricYou1987** [comment]
我找到原因了  api的文件格式错误，我想知道  hrun可以把har文件生成testcase类型文件，有没有生成api类型文件的功能？如果没有，打算自己改了

**Comment by EricYou1987** [comment]
找到原因了， api格式错误  不符合demo

**Comment by Xiaomin1210** [comment]
我也遇到了这个问题，具体是怎么样解决呀
