### ISSUE TITLE
在 testcase yaml 文件 - config 中为变量设置值时使用 $$ 未转换为普通的 $ 

### ISSUE THREAD

**Issue by ZitherPeng** [httprunner/httprunner#657]
## 问题描述

在 testcase yaml 文件 - config 中为变量设置值时使用 $$ 未转换为普通的 $ 。

在如下源码中看到需要使用 $ 做为普通字符时，可使用 $$ 表示:
```python
# content is in string format here
if not is_var_or_func_exist(content):
    # content is neither variable nor function
    # replace $$ notation with $ and consider it as normal char.
    # e.g. abc => abc, abc$$def => abc$def, abc$$$$def$$h => abc$$def$h
    return content.replace("$$", "$")
```

经测试在 api 描述文件和 testcase 的 teststep 中设置变量使用到 $ 符时都可以成功生效，如：
```yaml
- config:
    name: xxxx
      
- test:
    name: xxxx
    api: api/xx/xxxx.yaml
    variables:
      command: ifconfig | awk '{print $$5}'
```
如下，在 testcase 的 teststep 中设置变量值时，却无法生效，报错为（详见堆栈信息）： httprunner.exceptions.VariableNotFound: 5
```yaml
- config:
    name: xxxx
    variables:
      command: ifconfig | awk '{print $$5}'
      
- test:
    name: xxxx
    api: api/xx/xxxx.yaml
```

## 版本信息

 - 操作系统类型: macos
 - Python 版本 Python 3.7.3
 - HttpRunner 版本 2.1.2

## 运行命令 && 堆栈信息

请提供在命令行中运行测试时所在的目录和命令，以及报错时的详细堆栈内容。

```bash
$ pwd                                                                                                                                                                         
/Users/mac/project/pyProject/pgyboard_webapi

$ hrun --log-level debug testcases/mtu/s_setMTU.yaml
INFO     Loading environment variables from /Users/mac/project/pyProject/pgyboard_webapi/.env
DEBUG    Set OS environment variable: SN
DEBUG    Set OS environment variable: PASSWORD
DEBUG    Set OS environment variable: PGYBOX
DEBUG    Set OS environment variable: BASE_URL
DEBUG    Set OS environment variable: HTTPS_VERIFY
DEBUG    Set OS environment variable: User-Agent
/Users/mac/application/miniconda/envs/httprunner/lib/python3.7/site-packages/httprunner/loader.py:38: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  yaml_content = yaml.load(stream)
ERROR    !!!!!!!!!! exception stage: parse tests !!!!!!!!!!
Traceback (most recent call last):
  File "/Users/mac/application/miniconda/envs/httprunner/bin/hrun", line 10, in <module>
    sys.exit(main_hrun())
  File "/Users/mac/application/miniconda/envs/httprunner/lib/python3.7/site-packages/httprunner/cli.py", line 83, in main_hrun
    runner.run(path, dot_env_path=args.dot_env_path)
  File "/Users/mac/application/miniconda/envs/httprunner/lib/python3.7/site-packages/httprunner/api.py", line 264, in run
    return self.run_path(path_or_tests, dot_env_path, mapping)
  File "/Users/mac/application/miniconda/envs/httprunner/lib/python3.7/site-packages/httprunner/api.py", line 252, in run_path
    return self.run_tests(tests_mapping)
  File "/Users/mac/application/miniconda/envs/httprunner/lib/python3.7/site-packages/httprunner/api.py", line 171, in run_tests
    parsed_testcases = parser.parse_tests(tests_mapping)
  File "/Users/mac/application/miniconda/envs/httprunner/lib/python3.7/site-packages/httprunner/parser.py", line 1250, in parse_tests
    parsed_testcase = _parse_testcase(testcase, project_mapping)
  File "/Users/mac/application/miniconda/envs/httprunner/lib/python3.7/site-packages/httprunner/parser.py", line 1033, in _parse_testcase
    session_variables_set
  File "/Users/mac/application/miniconda/envs/httprunner/lib/python3.7/site-packages/httprunner/parser.py", line 895, in __prepare_config
    prepared_config = prepare_lazy_data(config, functions, check_variables_set, cached=True)
  File "/Users/mac/application/miniconda/envs/httprunner/lib/python3.7/site-packages/httprunner/parser.py", line 591, in prepare_lazy_data
    cached
  File "/Users/mac/application/miniconda/envs/httprunner/lib/python3.7/site-packages/httprunner/parser.py", line 591, in prepare_lazy_data
    cached
  File "/Users/mac/application/miniconda/envs/httprunner/lib/python3.7/site-packages/httprunner/parser.py", line 608, in prepare_lazy_data
    content = LazyString(content, functions_mapping, check_variables_set, cached)
  File "/Users/mac/application/miniconda/envs/httprunner/lib/python3.7/site-packages/httprunner/parser.py", line 445, in __init__
    self.__parse(raw_string)
  File "/Users/mac/application/miniconda/envs/httprunner/lib/python3.7/site-packages/httprunner/parser.py", line 508, in __parse
    raise exceptions.VariableNotFound(var_name)
httprunner.exceptions.VariableNotFound: 5
```

**Comment by ZitherPeng** [comment]
示例 yaml 文件：
```yaml
- config:
    name: testcase description
    verify: False
    variables:
      test_var: $$4

- test:
    name: /json
    variables:
      test_var: $$4
    request:
      method: GET
      url: https://httpbin.org/json
    validate:
      - eq:
          - status_code
          - 200
      - eq:
          - headers.Content-Type
          - application/json
```

**Comment by WonderfulGrayWolf** [comment]
有解决方案了嘛？
