### ISSUE TITLE
接口迁移过程中 POST请求405

### ISSUE THREAD

**Issue by orzcncn** [HttpRunner/HttpRunner#67]
从postman手动迁移接口成.yml文件  不少用例POST的方法返回status_code是405  
但是我使用其他工具和浏览器调试模式 都是200  

> 部分同时支持GET/POST请求的接口修改成GET请求后OK了 但是不支持的接口有没有什么解决方法

具体报错如下
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\httprunner\task.py", line 18, in runTest
    self.assertTrue(self.test_runner._run_test(self.testcase_dict))
  File "C:\Python27\lib\site-packages\httprunner\runner.py", line 132, in _run_test
    resp_obj.validate(validators, self.context.get_testcase_variables_mapping())
  File "C:\Python27\lib\site-packages\httprunner\response.py", line 173, in validate
    check_item
  File "C:\Python27\lib\site-packages\httprunner\utils.py", line 192, in match_expected
    raise exception.ValidationError(err_msg)
ValidationError: check item name: status_code;
check item value: 405 (int);
comparator: eq;
expected value: 200 (int).

**Comment by debugtalk** [comment]
@orzcncn 建议你在通过httprunner调用接口的时候进行抓包，再用抓包内容与原始的抓包内容进行对比，找出其中的差异。
