### ISSUE TITLE
关于执行setup_hooks和teardown_hooks之后返回变量的问题

### ISSUE THREAD

**Issue by ChenAlize** [httprunner/httprunner#672]
## 问题描述

在使用setup_hooks时,尝试对函数的返回值进行接收，于是查看源码时看到：
```python
    def do_hook_actions(self, actions, hook_type):
        """ call hook actions.

        Args:
            actions (list): each action in actions list maybe in two format.

                format1 (dict): assignment, the value returned by hook function will be assigned to variable.
                    {"var": "${func()}"}
                format2 (str): only call hook functions.
                    ${func()}

            hook_type (enum): setup/teardown

        """
        logger.log_debug("call {} hook actions.".format(hook_type))
        for action in actions:

            if isinstance(action, dict) and len(action) == 1:
                # format 1
                # {"var": "${func()}"}
                var_name, hook_content = list(action.items())[0]
                hook_content_eval = self.session_context.eval_content(hook_content)
                logger.log_debug(
                    "assignment with hook: {} = {} => {}".format(
                        var_name, hook_content, hook_content_eval
                    )
                )
                self.session_context.update_test_variables(
                    var_name, hook_content_eval
                )
            else:
                # format 2
                logger.log_debug("call hook function: {}".format(action))
                # TODO: check hook function if valid
                self.session_context.eval_content(action)
```
在`api`类型的YAML文件中设置setup_hooks和teardown_hooks，调用函数并接收返回值
```YAML
name: 开发者登录
base_url: https://api.apiopen.top
variables:
    developer_name: dev
    passwd: 123456
    success_code: 200
request:
    method: POST
    url: /developerLogin
    data:
        name: $developer_name
        passwd: $passwd
extract:
    apikey: content.result.apikey
validate:
    - eq: [content.code,$success_code]
setup_hooks:
    - req: ${setupRequest($request)}
teardown_hooks:
    - ${hook_print($req)}
```
运行之后报错，报错信息详见堆栈信息
## 版本信息

请提供如下版本信息：

 - 操作系统类型:  Windows
 - Python 版本: 3.6.3
 - HttpRunner 版本: 2.2.5

## 运行命令 && 堆栈信息

```bash
INFO     HttpRunner version: 2.2.5
INFO     Loading environment variables from D:\SL\httprunner\tests\.env
Traceback (most recent call last):
  File "D:/SL/httprunner/tests/test_run_yaml.py", line 6, in <module>
    runner.run("D:\SL\httprunner\\tests\\api\developer_login.yml")
  File "D:\SL\httprunner\httprunner\api.py", line 275, in run
    return self.run_path(path_or_tests, dot_env_path, mapping)
  File "D:\SL\httprunner\httprunner\api.py", line 263, in run_path
    return self.run_tests(tests_mapping)
  File "D:\SL\httprunner\httprunner\api.py", line 183, in run_tests
    parsed_testcases = parser.parse_tests(tests_mapping)
  File "D:\SL\httprunner\httprunner\parser.py", line 1259, in parse_tests
    parsed_testcase = _parse_testcase(testcase, project_mapping)
  File "D:\SL\httprunner\httprunner\parser.py", line 1037, in _parse_testcase
    session_variables_set
  File "D:\SL\httprunner\httprunner\parser.py", line 1009, in __prepare_testcase_tests
    teststep_variables_set
  File "D:\SL\httprunner\httprunner\parser.py", line 588, in prepare_lazy_data
    cached
  File "D:\SL\httprunner\httprunner\parser.py", line 572, in prepare_lazy_data
    for item in content
  File "D:\SL\httprunner\httprunner\parser.py", line 572, in <listcomp>
    for item in content
  File "D:\SL\httprunner\httprunner\parser.py", line 605, in prepare_lazy_data
    content = LazyString(content, functions_mapping, check_variables_set, cached)
  File "D:\SL\httprunner\httprunner\parser.py", line 443, in __init__
    self.__parse(raw_string)
  File "D:\SL\httprunner\httprunner\parser.py", line 492, in __parse
    self.check_variables_set
  File "D:\SL\httprunner\httprunner\parser.py", line 357, in __init__
    self.__parse(function_meta)
  File "D:\SL\httprunner\httprunner\parser.py", line 373, in __parse
    self.check_variables_set
  File "D:\SL\httprunner\httprunner\parser.py", line 572, in prepare_lazy_data
    for item in content
  File "D:\SL\httprunner\httprunner\parser.py", line 572, in <listcomp>
    for item in content
  File "D:\SL\httprunner\httprunner\parser.py", line 605, in prepare_lazy_data
    content = LazyString(content, functions_mapping, check_variables_set, cached)
  File "D:\SL\httprunner\httprunner\parser.py", line 443, in __init__
    self.__parse(raw_string)
  File "D:\SL\httprunner\httprunner\parser.py", line 505, in __parse
    raise exceptions.VariableNotFound(var_name)
httprunner.exceptions.VariableNotFound: req
```
在parser.py的__prepare_testcase_tests方法中，setup_hooks和teardown_hooks定义的变量名称并没有加入到teststep_variables_set中

**Comment by ChenAlize** [comment]
如果在testcase中定义有将hook函数返回值设置为变量的格式，即：
```YAML
setup_hooks:
    - req: ${setupRequest($request)}
teardown_hooks:
    - ${hook_print($req)}
```
那么，在运行testcase时，会报错，报错信息如下：
```bash
INFO     HttpRunner version: 2.2.5
INFO     Loading environment variables from D:\SL\httprunner\tests\.env
DEBUG    Set OS environment variable: UserName
DEBUG    Set OS environment variable: Password
DEBUG    Set OS environment variable: PROJECT_KEY
Traceback (most recent call last):
  File "D:/SL/httprunner/tests/test_run_yaml.py", line 6, in <module>
    runner.run("D:\SL\httprunner\\tests\\testcases\dev_login.yml")
  File "D:\SL\httprunner\httprunner\api.py", line 275, in run
    return self.run_path(path_or_tests, dot_env_path, mapping)
  File "D:\SL\httprunner\httprunner\api.py", line 263, in run_path
    return self.run_tests(tests_mapping)
  File "D:\SL\httprunner\httprunner\api.py", line 183, in run_tests
    parsed_testcases = parser.parse_tests(tests_mapping)
  File "D:\SL\httprunner\httprunner\parser.py", line 1260, in parse_tests
    parsed_testcase = _parse_testcase(testcase, project_mapping)
  File "D:\SL\httprunner\httprunner\parser.py", line 1050, in _parse_testcase
    session_variables_set
  File "D:\SL\httprunner\httprunner\parser.py", line 967, in __prepare_testcase_tests
    _extend_with_api(test_dict, api_def_dict)
  File "D:\SL\httprunner\httprunner\parser.py", line 819, in _extend_with_api
    extended_setup_hooks = list(set(def_setup_hooks + ref_setup_hooks))
TypeError: unhashable type: 'dict'
```

**Comment by yidaxia** [comment]
我也遇到了这个问题，同问

**Comment by chenliangtang** [comment]
我也提了类似的问题，我现在直接在 hook 函数的内部做校验

**Comment by ChenAlize** [comment]
按照源码中的写法，hooks中方法的返回值赋值到变量是可以成功的，上面描述的报错都是在检查和生成test的时候出现的错误
但是hooks中$request和$response这两个可变dict的存在，使得真正需要将hooks处理后的数据赋值到变量中的场景并不多
如果一定要的话，现阶段需要去修改源码

**Comment by ryanrain2016** [comment]
偷看源码之后遇到同样的问题， 然后通过钩子函数修改response，加上extract关键字实现的，
response对象可以随机加属性， 可以起到传递任意对象的作用
