### ISSUE TITLE
新增 --no-html-report 参数，运行后不生成测试报告

### ISSUE THREAD

**Issue by hazer491** [httprunner/httprunner#735]
## 问题描述
比如我用db来管理api，特别是mongo这种文档型数据库， api的定义完全可以放在db里面。
这样我跑api的时候是不是可以不用生成json或者yml文件？
类似的问题，现在是不不支持--no-html-report参数了？
我想结果直接存db， 没必要生成report文件。

**Comment by debugtalk** [comment]
@hazer491 

1、你可以将 HttpRunner 当作一个库来调用。
HttpRunner().run() 不仅可以传入 YAML/JSON 文件，也可以传入 JSON 结构体。

2、当前的确是不支持 --no-html-report 参数，这个后续可以添加下。

**Comment by hazer491** [comment]
@debugtalk 
runner.run(testcase)
当testcase是json结构体时，报错：
Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm Edu 2019.1.1\helpers\pydev\pydevd.py", line 1758, in <module>
INFO     HttpRunner version: 2.3.1
    main()
  File "C:\Program Files\JetBrains\PyCharm Edu 2019.1.1\helpers\pydev\pydevd.py", line 1752, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "C:\Program Files\JetBrains\PyCharm Edu 2019.1.1\helpers\pydev\pydevd.py", line 1147, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm Edu 2019.1.1\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:/Users/shiji/BT/tools/Python3/test_httprunner/cli.py", line 38, in <module>
    runner.run(case_path,mapping=mapping)
  File "C:\Users\shiji\Python37\lib\site-packages\httprunner\api.py", line 279, in run
    raise exceptions.ParamsError("Invalid testcase path or testcases: {}".format(path_or_tests))
httprunner.exceptions.ParamsError: Invalid testcase path or testcases: [{'config': {'name': 'test', 'variables': {}, 'base_url': 'http://www.baidu.com'}, 'test': {'name': 'step 1', 'variables': {}, 'validate': [], 'request': {'url': '/', 'method': 'GET', 'headers': {}, 'verify': False}}}]

**Comment by debugtalk** [comment]
从 2.3.2 版本开始，运行测试和生成 HTML 测试报告进行了解耦。
调用 HttpRunner().run() 后返回 summary 数据。
