### ISSUE TITLE
testcase 变量 提取 /传递 问题

### ISSUE THREAD

**Issue by yexuesong** [httprunner/httprunner#743]
## 问题描述

在登录页面获取了一个字符串，该字符串在之后的POST 请求的 data 中一直需要使用到，目的是防止跨站攻击。

我现在需要传递该 token，但是 testcase 不能在调用其他 testcase时获取其参数，只能传入。

现在想到的解决方法是使用 hook 获取 response，然后自己解析html获取 token，然后再通过函数调用把这个参数返回到要用的地方。

请问可以提供该功能或者别的方案吗？

**Comment by yexuesong** [comment]
我现在于 debugtalk 中使用如下方法提取

```python
from bs4 import BeautifulSoup

c_token=""

def parser_ctoken(response):
    soup = BeautifulSoup(response.text, "html.parser")
    input_tag = soup.find('input', id='ctoken')
    c_token = input_tag['value']
    return c_token

def get_ctoken():
    return c_token

def main():
    c_token = parser_ctoken()
    get_ctoken(c_token)
```

请问为什么 teardown 获取 response 会有如下报错？

```bash
Traceback (most recent call last):
  File "c:\users\yexuesong\.virtualenvs\httptest\lib\site-packages\httprunner\api.py", line 55, in test
    test_runner.run_test(test_dict)
  File "c:\users\yexuesong\.virtualenvs\httptest\lib\site-packages\httprunner\runner.py", line 376, in run_test
    self._run_test(test_dict)
  File "c:\users\yexuesong\.virtualenvs\httptest\lib\site-packages\httprunner\runner.py", line 262, in _run_test
    self.do_hook_actions(teardown_hooks, "teardown")
  File "c:\users\yexuesong\.virtualenvs\httptest\lib\site-packages\httprunner\runner.py", line 149, in do_hook_actions
    for action in actions:
TypeError: 'LazyString' object is not iterable
```

**Comment by hazer491** [comment]
看不到代码，不好说问题出在什么地方。
我觉得可以用suite， 在suite的config里面定义一个变量用来获取token.
然后， 每个case就都可以用到这个token了。至于怎么用，可以增加一个hook函数，用来处理token。

**Comment by yexuesong** [comment]
@hazer491 
你的意思是在 testsuite 里面提供一个变量，该变量的值来自于 debugtalk 里面我自己编写的函数，该函数用requests去获取登录页面并拿到 token 嘛。

这样是不可以的，因为我自己编写的函数去获取 token 的 session 和 testcase 里登录的 session 会不同。我并没有找到传递自己编写函数的 session 到 httprunner 的方法。

**Comment by yexuesong** [comment]
这个和 testsuite 也没有关系吧，只是在 yml 文件中可以通过 `${function()}` 的形式引用函数的返回值，我这样时可以自定义获取到 `token`，但是 session 不共享，没有用，这个也是我需要将 yml 方式获取到的 ctoken 提取出来的原因，目前我做不到提取出来。

**Comment by hazer491** [comment]
一个suite里面的case都是跑在一个session里面的吧。
你通过 ${function()}这种方式， 每个case都需要取一次token， 放到config， 一个suite只需要取一次token

**Comment by yexuesong** [comment]
问题是 `token` 是我自己 `import requests` 取的，和 `case` 无法共享 `session` 的。

**Comment by hazer491** [comment]
你可以在debugtalk里面封装一个取token的方法,然后再config里面定义一个变量来接收token。
这样suite config的变量就是全局的， 每个case都能拿来用。

**Comment by zlinghuvip123** [comment]
先确认一下你的问题：
你希望登录之后获取到token值后，后面其他的接口都用到这个token值？
如果是这样，那么这个问题可以通过以下方法解决：
1. 要保证每个测试用例的独立性，所以在每个测试用例之前都加上登录操作这个step. 不能做到一个登录完了后，获取到的token值给其它所有的case使用。 
2. 提取token的时候可以不使用自定义方法，可以通过正则表达式来提取登录请求返回的页面中的token值。

希望以上的解决方案能帮到你。

**Comment by yexuesong** [comment]
我目前就是这么用的，但是这个方法不简洁。我依然希望可以提供一个可选项，也不认为提供之后会破坏“独立性”，所以先让这个问题保持 Open 状态，看看作者的意见吧，如果他有时间处理的话。

**Comment by jackiezero** [comment]
不确实你的问题是否是，先登陆，然后取出token，再给其他case使用，
如果是的话，
1. 先别登陆写一个case，然后通过output 提取出来
2. 在其他case中的第一个step引用这个case，

**Comment by esnhysythh** [comment]
个人认为，这个是hook机制比较匮乏的问题，
之前使用过pytest，它的机制就能很好的解决这个问题，
pytest可以做到详细规定这些setup方法的级别，
比如对于登录获取token这种操作，一次测试只需要进行一次，就可以设为session级别。

目前我的解决方式是这样的：
设置许多全局变量，存放到一个名叫config的模块中，
在debugtalk中设置一个函数get_token( )，

~~~~~~~~~~~~~~~~
from common import config #这是控制全局变量的模块
from common.util import token_util # 这是获取token的相关方法

def get_token():
  # 如果之前没有获取过token
  if config.get_value('has_token') == False:
    token = token_util.get_token() #通过http请求获取token的方法
    config.set_value('token') = token #将token获取到的值存入全局变量
    config.set_value('has_token') = True #重设标记量，证明已经获取过token
  # 如果之前获取过token
  else:
    token = config.get_value('token') #直接从全局变量中拿token
  return token

~~~~~~~~~~~~~~~~~

这样相当于通过全局变量的标记，让获取token的http请求只用执行一次。
当然，个人还是希望能引入类似pytest中的相关机制，这样就会省事很多
