### ISSUE TITLE
登录参数化后运行报错

### ISSUE THREAD

**Issue by liucuiying2019** [httprunner/httprunner#745]
## 问题描述
登录参数化后运行报错
请对遇到的 bug 进行简要描述。
1、对登录的yml进行分层分级
2、对登录账号和密码进行参数化，将其写入csv
**testsuites\loginout_parameters.yml**
- config:
    name: "users login and logout"
    id: user login and logout
    parameters:
        user-password: {P(data/account1.csv)}
        
- test:
    name: user login and logout
    testcase: testcases/loginout.yml

**testcases/loginout.yml**
- config:
    name: "login and logout"
    id: login_and_logout 
    base_url: http://xxx.com

- test:
    name: login
    api: api/login.yml

- test:
    name: logout
    api: api/logout.yml

**api/login.yml**
name: /api/v1/account/login
base_url:http://xxx.com
variables:

request:
    url: /api/v1/account/login
    method: POST
    headers:
        Content-Type: application/json;charset=UTF-8
        User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36
                (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36
        device-sign: 77f58cf6562135128d6c6b814252d604
    json:
        code: $user
        password: $password
validate:
    - eq: ["status_code", 200]
    - eq: ["headers.Content-Type", "application/json; charset=utf-8"]

**api/logout.yml**
name: /api/v1/account/logout
base_url: http://xxx.com
variables:

request:
    url: /api/v1/account/logout
    method: POST
    data: ''
    headers:
        User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36
                (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36
        device-sign: 77f58cf6562135128d6c6b814252d604
validate:
    - eq: ["status_code", 200]
    - eq: ["headers.Content-Type", "application/json; charset=utf-8"]
    - eq: ["content.code", 0]
    - eq: ["content.message", "OK"]

3、使用命令行运行，报错httprunner.exceptions.VariableNotFound: user

## 版本信息

请提供如下版本信息：

 - 操作系统类型: [e.g. Windows10]
 - Python 版本 [e.g. 3.6.3]
 - HttpRunner 版本 [e.g. 2.3.2]

## 项目文件内容（非必须）
F:\HttpRunner\login>hrun testsuites\loginout_parameters.yml
INFO     HttpRunner version: 2.3.2
!!!!!!!!!! exception stage: parse tests !!!!!!!!!!
Traceback (most recent call last):
  File "e:\program files\python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "e:\program files\python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "E:\Program Files\Python36\Scripts\hrun.exe\__main__.py", line 9, in <module>
  File "e:\program files\python36\lib\site-packages\httprunner\cli.py", line 95, in main
    summary = runner.run(path, dot_env_path=args.dot_env_path)
  File "e:\program files\python36\lib\site-packages\httprunner\api.py", line 282, in run
    return self.run_path(path_or_tests, dot_env_path, mapping)
  File "e:\program files\python36\lib\site-packages\httprunner\api.py", line 266, in run_path
    return self.run_tests(tests_mapping)
  File "e:\program files\python36\lib\site-packages\httprunner\api.py", line 191, in run_tests
    parsed_testcases = parser.parse_tests(tests_mapping)
  File "e:\program files\python36\lib\site-packages\httprunner\parser.py", line 1259, in parse_tests
    parsed_testcase = _parse_testcase(testcase, project_mapping)
  File "e:\program files\python36\lib\site-packages\httprunner\parser.py", line 1049, in _parse_testcase
    session_variables_set
  File "e:\program files\python36\lib\site-packages\httprunner\parser.py", line 973, in __prepare_testcase_tests
    test_dict = _parse_testcase(test_dict, project_mapping, session_variables_set)
  File "e:\program files\python36\lib\site-packages\httprunner\parser.py", line 1049, in _parse_testcase
    session_variables_set
  File "e:\program files\python36\lib\site-packages\httprunner\parser.py", line 1021, in __prepare_testcase_tests
    teststep_variables_set
  File "e:\program files\python36\lib\site-packages\httprunner\parser.py", line 587, in prepare_lazy_data
    cached
  File "e:\program files\python36\lib\site-packages\httprunner\parser.py", line 587, in prepare_lazy_data
    cached
  File "e:\program files\python36\lib\site-packages\httprunner\parser.py", line 587, in prepare_lazy_data
    cached
  File "e:\program files\python36\lib\site-packages\httprunner\parser.py", line 604, in prepare_lazy_data
    content = LazyString(content, functions_mapping, check_variables_set, cached)
  File "e:\program files\python36\lib\site-packages\httprunner\parser.py", line 442, in __init__
    self.__parse(raw_string)
  File "e:\program files\python36\lib\site-packages\httprunner\parser.py", line 504, in __parse
    raise exceptions.VariableNotFound(var_name)
httprunner.exceptions.VariableNotFound: user

**Comment by zlinghuvip123** [comment]
parameters 位置放错了？

testsuites\loginout_parameters.yml

config:
name: "users login and logout"
id: user login and logout

test:
name: user login and logout
testcase: testcases/loginout.yml
parameters:
user-password: {P(data/account1.csv)}

**Comment by liucuiying2019** [comment]
谢谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"t-bug"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月19日(星期二) 下午4:01
收件人:&nbsp;"httprunner/httprunner"<httprunner@noreply.github.com&gt;;
抄送:&nbsp;"盈子"<lindaliucy@foxmail.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [httprunner/httprunner] 登录参数化后运行报错 (#745)




parameters 位置放错了？
 
testsuites\loginout_parameters.yml
 
config:
 name: "users login and logout"
 id: user login and logout
 
test:
 name: user login and logout
 testcase: testcases/loginout.yml
 parameters:
 user-password: {P(data/account1.csv)}
