### ISSUE TITLE
testcases中文件夹job,job文件夹下有很多testcases，hrun job文件夹，只有最后一个case运行成功，其余case都是未登录

### ISSUE THREAD

**Issue by 15771929834** [httprunner/httprunner#754]
## 问题描述

testcases中文件夹job，job文件夹下有很多testcases，hrun job文件夹，只有最后一个case运行成功，其余case都是未登录。
![image](https://user-images.githubusercontent.com/50389760/69055566-08844d00-0a49-11ea-8909-d6d2c40df600.png)
![image](https://user-images.githubusercontent.com/50389760/69055759-847e9500-0a49-11ea-9549-d960c0c23faf.png)

## 版本信息
INFO     HttpRunner version: 2.3.2
!!!!!!!!!! exception stage: initialize HttpRunner() !!!!!!!!!!

请提供如下版本信息：

 - 操作系统类型: linux
 - Python 版本 3.7
 - HttpRunner 版本 2.3.2

## 项目文件内容（非必须）

每个testcase中都调用了获取cookies的方法，单独执行每个testcase都成功，使用hrun job文件夹所在路径，只有最后一个运行成功，其余都显示未登录

## 运行命令 && 堆栈信息

请提供在命令行中运行测试时所在的目录和命令，以及报错时的详细堆栈内容。
部分截图如下，但其余报错都是: 401 - Unauthorized ERROR

FAIL: test_0000_000 (httprunner.api.TestSequense)
trash list
----------------------------------------------------------------------
Traceback (most recent call last):
  File "e:\python37-32\lib\site-packages\httprunner\api.py", line 61, in test
    test_runner.run_test(test_dict)
httprunner.exceptions.ExtractFailure: Failed to extract attribute from response body! => content.data
response body: version[ca329aa9_ca329aa9]: 401 - Unauthorized ERROR

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "e:\python37-32\lib\site-packages\httprunner\api.py", line 63, in test
    self.fail(str(ex))
AssertionError: Failed to extract attribute from response body! => content.data
response body: version[ca329aa9_ca329aa9]: 401 - Unauthorized ERROR

**Comment by Aqiu007** [comment]
我也是，单独运行一个用例是成功的，全部一起运行就报错，后来看日志定位到是多个用例有同名变量导致的。
