### ISSUE TITLE
testcase中validate解析失败

### ISSUE THREAD

**Issue by Kewings** [httprunner/httprunner#772]
## 问题描述

```
- config:
    name: Lidar Set IP Destination
    base_url: "${BaseHost()}"

- test:
    name: set dst ip $ip_disnation
    api: api/Set/02set_ip_disnation.yml
    variables:
      ip_disnation: '{"IPv4":"255.255.255.255","Port":2368,"GpsPort":10110}'

- test:
    name: get dst ip $ip_disnation
    api: api/Get/03get_lidar_config.yml
    validate:
        - lt: [content.Body.DestIp, ${gen_dict_to_string($ip_disnation)}]
        - lt: [content.Body.DestPort, ${gen_dict_to_string($ip_disnation)}]
        - lt: [content.Body.GpsPort, ${gen_dict_to_string($ip_disnation)}]
```

报错信息：
```
Traceback (most recent call last):
  File "D:/Code/Lidar_API/APIRunner.py", line 63, in <module>
    API_main()
  File "D:/Code/Lidar_API/APIRunner.py", line 32, in API_main
    summary = runner.run(testsets)
  File "C:\Python3\lib\site-packages\httprunner\api.py", line 282, in run
    return self.run_path(path_or_tests, dot_env_path, mapping)
  File "C:\Python3\lib\site-packages\httprunner\api.py", line 260, in run_path
    tests_mapping = loader.load_tests(path, dot_env_path)
  File "C:\Python3\lib\site-packages\httprunner\loader.py", line 907, in load_tests
    __load_file_content(path)
  File "C:\Python3\lib\site-packages\httprunner\loader.py", line 888, in __load_file_content
    loaded_content = load_test_file(path)
  File "C:\Python3\lib\site-packages\httprunner\loader.py", line 609, in load_test_file
    raw_content = load_file(path)
  File "C:\Python3\lib\site-packages\httprunner\loader.py", line 117, in load_file
    return load_yaml_file(file_path)
  File "C:\Python3\lib\site-packages\httprunner\loader.py", line 46, in load_yaml_file
    yaml_content = yaml.load(stream)
  File "C:\Python3\lib\site-packages\yaml\__init__.py", line 114, in load
    return loader.get_single_data()
  File "C:\Python3\lib\site-packages\yaml\constructor.py", line 41, in get_single_data
    node = self.get_single_node()
  File "C:\Python3\lib\site-packages\yaml\composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "C:\Python3\lib\site-packages\yaml\composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "C:\Python3\lib\site-packages\yaml\composer.py", line 82, in compose_node
    node = self.compose_sequence_node(anchor)
  File "C:\Python3\lib\site-packages\yaml\composer.py", line 111, in compose_sequence_node
    node.value.append(self.compose_node(node, index))
  File "C:\Python3\lib\site-packages\yaml\composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "C:\Python3\lib\site-packages\yaml\composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "C:\Python3\lib\site-packages\yaml\composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "C:\Python3\lib\site-packages\yaml\composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "C:\Python3\lib\site-packages\yaml\composer.py", line 82, in compose_node
    node = self.compose_sequence_node(anchor)
  File "C:\Python3\lib\site-packages\yaml\composer.py", line 111, in compose_sequence_node
    node.value.append(self.compose_node(node, index))
  File "C:\Python3\lib\site-packages\yaml\composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "C:\Python3\lib\site-packages\yaml\composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "C:\Python3\lib\site-packages\yaml\composer.py", line 82, in compose_node
    node = self.compose_sequence_node(anchor)
  File "C:\Python3\lib\site-packages\yaml\composer.py", line 110, in compose_sequence_node
    while not self.check_event(SequenceEndEvent):
  File "C:\Python3\lib\site-packages\yaml\parser.py", line 98, in check_event
    self.current_event = self.state()
  File "C:\Python3\lib\site-packages\yaml\parser.py", line 484, in parse_flow_sequence_entry
    "expected ',' or ']', but got %r" % token.id, token.start_mark)
yaml.parser.ParserError: while parsing a flow sequence
  in "D:\Code\Lidar_API\TestCase\2.9.3\Lidar_SetIPDestination.yml", line 15, column 15
expected ',' or ']', but got '{'
  in "D:\Code\Lidar_API\TestCase\2.9.3\Lidar_SetIPDestination.yml", line 15, column 38
```

## 版本信息

请提供如下版本信息：

 - 操作系统类型: [ Windows]
 - Python 版本 [3.7.3]
 - HttpRunner 版本 [2.3.2]

**Comment by Kewings** [comment]
试了好多次，发现是在testcase层级，写在debugtalk.py中的函数调用都失败

**Comment by esnhysythh** [comment]
手头没有python，凭印象：
$ip_disnation 是一个变量，
这个变量应该是从【当前teststep】或者testcase的variables里面取的，
你在前面一个step的variables里面放了那个变量，
当前teststep没有这个参数，当然会出问题。

尝试将$ip_disnation 放入config的variables中
~~~~~~~~~~
config:
    name: Lidar Set IP Destination
    base_url: "${BaseHost()}"
    variables:
        ip_disnation: '{"IPv4":"255.255.255.255","Port":2368,"GpsPort":10110}'

**Comment by lingati** [comment]
在校验器里试图使用环境变量${ENV(USERNAME)}时出现同样的问题，报错也是因为遇到了大括号"{"。
我临时的解决方案是把期望结果放到variables，然后校验器调用变量。

- config:
    name: Lidar Set IP Destination
    base_url: "${BaseHost()}"
    variables:
        expect_result: ${gen_dict_to_string($ip_disnation)}

- test:
    name: get dst ip $ip_disnation
    api: api/Get/03get_lidar_config.yml
    validate:
        - lt: [content.Body.DestIp, expect_result]
        - lt: [content.Body.DestPort, expect_result]
        - lt: [content.Body.GpsPort, expect_result]

**Comment by Kewings** [comment]
试了，确实解决了，谢谢@lingati 和@esnhysythh
