### ISSUE TITLE
debugtalk里面的方法无法传JSON或者数组类型的参数

### ISSUE THREAD

**Issue by clh962464** [httprunner/httprunner#873]
## 问题描述
在debugtalk中，传入json或者数组类型的参数无法识别执行
请对遇到的 bug 进行简要描述。
在debugtalk中，传入json或者数组类型的参数无法识别执行

请提供如下版本信息：
 - 操作系统类型: Windows
 - Python 版本 [e3.6]
 - HttpRunner 版本 [e.g. 2.5.1]

## 运行命令 && 堆栈信息

请提供在命令行中运行测试时所在的目录和命令，以及报错时的详细堆栈内容。
Traceback (most recent call last):
  File "d:\python\python36\lib\site-packages\httprunner\api.py", line 54, in test
    test_runner.run_test(test_dict)
httprunner.exceptions.ValidationFailure: validate: content.responseEntity equals ${token({'c':'d'})}(str)       ==> fail
None(NoneType) equals ${token({'c':'d'})}(str)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\python\python36\lib\site-packages\httprunner\api.py", line 56, in test
    self.fail(str(ex))
AssertionError: validate: content.responseEntity equals ${token({'c':'d'})}(str)        ==> fail
None(NoneType) equals ${token({'c':'d'})}(str)

**Comment by zhoubihui** [comment]
我这边有一个类似的问题，我是直接传字符串，debug发现是正则判断的问题

**Comment by zhoubihui** [comment]
我这边也有一个类似的问题，传字符串给debugtalk的函数，在解析yaml文件时无法识别是个函数，debug后发现是正则校验问题

**Comment by zhoubihui** [comment]
我这边也有一个类似的问题，传字符串给debugtalk的函数，在解析yaml文件时无法识别是个函数，debug后发现是正则校验问题<br>yaml文件中：<br>![image.png](https://i.loli.net/2020/03/20/9sGcVTA8ndEZMC1.png)<br>httprunner读取yaml文件后：<br>![image.png](https://i.loli.net/2020/03/20/VFJs3Gc6yOM7Z4W.png)<br>debug后发现是函数正则判断不通过：<br>![image.png](https://i.loli.net/2020/03/20/v3WuJtODoSZ9zPl.png)<br>
