### ISSUE TITLE
httprunner 3.0.0的脚本 在用 3.0.5运行时 报'list' object has no attribute 'setdefault' 错误

### ISSUE THREAD

**Issue by StevenPZP** [httprunner/httprunner#914]
## 问题描述

httprunner 3.0.0的脚本 在用 3.0.5运行时 报'list' object has no attribute 'setdefault' 错误

## 版本信息
httprunner 3.0.5
python 3.7.4

## 问题代码
下面这个代码在加载之前的 用例文件时 返回的是list
```python
def load_test_file(test_file: Text) -> Dict:
    """load testcase/testsuite file content"""
    if not os.path.isfile(test_file):
        raise exceptions.FileNotFound(f"test file not exists: {test_file}")

    file_suffix = os.path.splitext(test_file)[1].lower()
    if file_suffix == ".json":
        test_file_content = _load_json_file(test_file)
    elif file_suffix in [".yaml", ".yml"]:
        test_file_content = _load_yaml_file(test_file)
    else:
        # '' or other suffix
        raise exceptions.FileFormatError(
            f"testcase/testsuite file should be YAML/JSON format, invalid format file: {test_file}"
        )

    return test_file_content

```

## 运行命令 && 堆栈信息
Connected to pydev debugger (build 192.6262.63)
Traceback (most recent call last):
  File "/Applications/PyCharm.app/Contents/helpers/pydev/pydevd.py", line 2060, in <module>
    main()
  File "/Applications/PyCharm.app/Contents/helpers/pydev/pydevd.py", line 2054, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/Applications/PyCharm.app/Contents/helpers/pydev/pydevd.py", line 1405, in run
    return self._exec(is_module, entry_point_fn, module_name, file, globals, locals)
  File "/Applications/PyCharm.app/Contents/helpers/pydev/pydevd.py", line 1412, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/Applications/PyCharm.app/Contents/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/Users/panzhipiao/workspace/testtools/debug.py", line 6, in <module>
    runner.run_path("testcases/03_订单/00_确认收货入账/现货-网银付款-确认收货-评价.yaml")
  File "/Users/panzhipiao/workspace/httprunner/httprunner/runner.py", line 224, in run_path
    testcase_obj = load_testcase_file(path)
  File "/Users/panzhipiao/workspace/httprunner/httprunner/loader.py", line 93, in load_testcase_file
    testcase_content.setdefault("config", {})["path"] = testcase_file
AttributeError: 'list' object has no attribute 'setdefault'

**Comment by debugtalk** [comment]
@StevenPZP 感觉是你的用例格式的问题，你的用例内容贴出来看下？

**Comment by dearestu** [comment]
我也遇到了，你怎么解决的

**Comment by debugtalk** [comment]
@dearestu 确定是个 bug，已修复，升级到最新版本即可。
