### ISSUE TITLE
ImportError: cannot import name 'NoReturn'

### ISSUE THREAD

**Issue by zhaohexiang-zhx** [httprunner/httprunner#968]
Traceback (most recent call last):
  File "e:\python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "e:\python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "E:\Python36\Scripts\hrun.exe\__main__.py", line 5, in <module>
  File "e:\python36\lib\site-packages\httprunner\__init__.py", line 7, in <modul
e>
    from httprunner.runner import HttpRunner
  File "e:\python36\lib\site-packages\httprunner\runner.py", line 5, in <module>

    from typing import List, Dict, Text, NoReturn
ImportError: cannot import name 'NoReturn'

**Comment by wuliang0418** [comment]
typing库版本的问题，降版本试试

**Comment by debugtalk** [comment]
@zhaohexiang-zhx 检查下你的 python 版本和环境。
