### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode characters in position 11-13: ordinal not in range(128)

### ISSUE THREAD

**Issue by dengly** [HttpRunner/HttpRunner#99]
运行测试用例后报以下错误，应该是字符编码处理有问题，因为返回结果里包含中文
```
ERROR [0.133801s]: /user/init
----------------------------------------------------------------------
Traceback (most recent call last):
UnicodeEncodeError: 'ascii' codec can't encode characters in position 11-13: ordinal not in range(128)

----------------------------------------------------------------------
Ran 2 tests in 0.375s

FAILED
 (Errors=1)

Generating HTML reports...
Template is not specified, load default template instead.
```

**Comment by debugtalk** [comment]
@dengly Python是什么版本，还有你安装的 HttpRunner 的版本 ？

**Comment by dengly** [comment]
HttpRunner version: 0.9.3
PyUnitReport version: 0.1.4

**Comment by dengly** [comment]
python 2.7

**Comment by debugtalk** [comment]
@dengly Python 2 可能会出现编码问题，如果可以，尽可能用 Python 3 吧。

另外，你运行测试的时候，开启 debug 模式，把报错的堆栈贴出来看下。

--log-level debug

**Comment by lumingjie** [comment]
遇到同样问题，报错信息如下：Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/httprunner/task.py", line 17, in runTest
    self.test_runner._run_test(self.testcase_dict)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/httprunner/runner.py", line 148, in _run_test
    **parsed_request
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/httprunner/client.py", line 120, in request
    response = self._send_request_safe_mode(method, url, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/httprunner/client.py", line 163, in _send_request_safe_mode
    return requests.Session.request(self, method, url, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/urllib3/connectionpool.py", line 357, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1284, in _send_request
    body = _encode(body, 'body')
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 161, in _encode
    (name.title(), data[err.start:err.end], name)) from None
UnicodeEncodeError: 'latin-1' codec can't encode characters in position 10-11: Body ('北京') is not valid Latin-1. Use body.encode('utf-8') if you want to send it encoded in UTF-8.

**Comment by debugtalk** [comment]
@dengly 看这个堆栈实在是看不出来原因，这应该跟你测试的接口有很大关系。

你有对接口进行抓包么？可否将抓包数据导出为 HAR 格式发给我？

**Comment by lumingjie** [comment]
[Untitled.har.zip](https://github.com/HttpRunner/HttpRunner/files/1753989/Untitled.har.zip)

**Comment by debugtalk** [comment]
@lumingjie 感谢！问题复现了，我修复下。

```json
[
    {
        "config": {
            "name": "testset description",
            "variables": [],
            "request": {
                "base_url": "",
                "headers": {
                    "User-Agent": "com.autoiots.freight.customer/1"
                }
            }
        }
    },
    {
        "test": {
            "name": "/manycc/enquiry/getPriceByCity",
            "request": {
                "url": "http://yuncc.changjiu56.com/manycc/enquiry/getPriceByCity",
                "headers": {
                    "If-Modified-Since": "Sat, 24 Feb 2018 01:51:41 GMT+00:00",
                    "Content-Type": "application/x-www-form-urlencoded; charset=UTF-8"
                },
                "method": "POST",
                "data": "from_addr=北京&to_addr=石家庄市"
            },
            "validate": [
                {
                    "eq": [
                        "status_code",
                        200
                    ]
                },
                {
                    "eq": [
                        "headers.Content-Type",
                        "text/html;charset=utf-8"
                    ]
                }
            ]
        }
    }
]
```

```bash
python main-debug.py hrun Untitled.json --log-level debug

Running tests...
----------------------------------------------------------------------
 /manycc/enquiry/getPriceByCity ... INFO     POST http://yuncc.changjiu56.com/manycc/enquiry/getPriceByCity
DEBUG    request kwargs: {'headers': {'User-Agent': 'com.autoiots.freight.customer/1', 'If-Modified-Since': 'Sat, 24 Feb 2018 01:51:41 GMT+00:00', 'Content-Type': 'application/x-www-form-urlencoded; charset=UTF-8'}, 'data': 'from_addr=北京&to_addr=石家庄市'}
DEBUG    Starting new HTTP connection (1): 127.0.0.1
ERROR (0.021176)s

======================================================================
ERROR [0.021176s]: b'\x1b[33m/manycc/enquiry/getPriceByCity'
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/debugtalk/MyProjects/HttpRunner-dev/HttpRunner/httprunner/task.py", line 17, in runTest
    self.test_runner._run_test(self.testcase_dict)
  File "/Users/debugtalk/MyProjects/HttpRunner-dev/HttpRunner/httprunner/runner.py", line 148, in _run_test
    **parsed_request
  File "/Users/debugtalk/MyProjects/HttpRunner-dev/HttpRunner/httprunner/client.py", line 119, in request
    response = self._send_request_safe_mode(method, url, **kwargs)
  File "/Users/debugtalk/MyProjects/HttpRunner-dev/HttpRunner/httprunner/client.py", line 162, in _send_request_safe_mode
    return requests.Session.request(self, method, url, **kwargs)
  File "/Users/debugtalk/.pyenv/versions/3.6.4/lib/python3.6/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/debugtalk/.pyenv/versions/3.6.4/lib/python3.6/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/Users/debugtalk/.pyenv/versions/3.6.4/lib/python3.6/site-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/Users/debugtalk/.pyenv/versions/3.6.4/lib/python3.6/site-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/Users/debugtalk/.pyenv/versions/3.6.4/lib/python3.6/site-packages/urllib3/connectionpool.py", line 357, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/Users/debugtalk/.pyenv/versions/3.6.4/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Users/debugtalk/.pyenv/versions/3.6.4/lib/python3.6/http/client.py", line 1284, in _send_request
    body = _encode(body, 'body')
  File "/Users/debugtalk/.pyenv/versions/3.6.4/lib/python3.6/http/client.py", line 161, in _encode
    (name.title(), data[err.start:err.end], name)) from None
UnicodeEncodeError: 'latin-1' codec can't encode characters in position 10-11: Body ('北京') is not valid Latin-1. Use body.encode('utf-8') if you want to send it encoded in UTF-8.

----------------------------------------------------------------------
Ran 1 test in 0.021s

FAILED
 (Errors=1)
```

**Comment by debugtalk** [comment]
@lumingjie @dengly 已经修复了。

修复后的运行情况：
```
$ python main-debug.py hrun Untitled.json --log-level debug

Running tests...
----------------------------------------------------------------------
 /manycc/enquiry/getPriceByCity ... INFO     POST http://yuncc.changjiu56.com/manycc/enquiry/getPriceByCity
DEBUG    request kwargs(raw): {'headers': {'user-agent': 'com.autoiots.freight.customer/1', 'if-modified-since': 'Sat, 24 Feb 2018 01:51:41 GMT+00:00', 'content-type': 'application/x-www-form-urlencoded; charset=UTF-8'}, 'data': 'from_addr=北京&to_addr=石家庄市'}
DEBUG    request kwargs(processed): {'headers': {'user-agent': 'com.autoiots.freight.customer/1', 'if-modified-since': 'Sat, 24 Feb 2018 01:51:41 GMT+00:00', 'content-type': 'application/x-www-form-urlencoded; charset=UTF-8'}, 'data': b'from_addr=\xe5\x8c\x97\xe4\xba\xac&to_addr=\xe7\x9f\xb3\xe5\xae\xb6\xe5\xba\x84\xe5\xb8\x82', 'timeout': 120}
DEBUG    Starting new HTTP connection (1): 127.0.0.1
DEBUG    http://127.0.0.1:8888 "POST http://yuncc.changjiu56.com/manycc/enquiry/getPriceByCity HTTP/1.1" 200 None
DEBUG    response status_code: 200
DEBUG    response headers: {'Server': 'Apache-Coyote/1.1', 'Content-Type': 'text/html;charset=utf-8', 'Date': 'Sat, 24 Feb 2018 07:33:33 GMT', 'Transfer-Encoding': 'chunked', 'Proxy-Connection': 'Close'}
DEBUG    response body: {"Action":{"retcode":"0","token":"","retmsg":"ok","type":""},"Data":[{"begin_park_id":"1101","code":"","down_payment":"","end_park_id":"1301","from_addr":"","id":"","insertTime":"","insertUser":"","insert_time":"","insert_user":"","line_id":"8a8083b56169506c01616a6e9bf50011","memo":"","name":"","odo":"300","price":"120000","remark":"","short_cost":"","sortNum":0,"state":"","to_addr":"","total_time":"3","updateTime":"","updateUser":"","update_time":"","update_user":""}]}
INFO     status_code: 200, response_time: 454 ms, response_length: 474 bytes
OK (0.456661)s

----------------------------------------------------------------------
Ran 1 test in 0.457s

OK
```
